### ISSUE TITLE
what is an exponential cone anyway?

### ISSUE THREAD

**Issue by mlubin** [JuliaOpt/Convex.jl#104]
Not quite an issue with Convex.jl, but seems like a good place to have a discussion with the DCP community. I've been playing a lot with exponential cones recently, especially ECOS as the world's first interior point solver with support for exponential cones (as far as I'm aware). The performance is encouraging, when it works, although convergence issues are a serious impediment (https://github.com/embotech/ecos/issues/134).

Here's a convex.jl model (don't ask where it came from) that's pretty simple overall, just a bunch of linear constraints, one nonlinear constraint, and a nonlinear objective: https://gist.github.com/mlubin/850e00cbdfd24906f787

If I run with ECOS, it runs fast but doesn't converge:
```
ECOS 2.0.4 - (C) embotech GmbH, Zurich Switzerland, 2012-15. Web: www.embotech.com/ECOS

It     pcost       dcost      gap   pres   dres    k/t    mu     step   sigma     IR    |   BT
 0  +0.000e+00  -1.426e+03  +2e+03  1e+00  2e+00  1e+00  1e+00    ---    ---    0  0  - |  -  - 
 1  -1.565e+03  -2.978e+03  +8e+02  4e-01  2e+00  2e+00  5e-01  0.7833  3e-01   2  2  2 |  0  1
 2  -2.591e+03  -3.987e+03  +6e+02  4e-01  2e+00  3e+00  3e-01  0.5013  5e-01   2  1  2 |  4  3
 3  -2.193e+03  -3.569e+03  +5e+02  4e-01  2e+00  3e+00  3e-01  0.9791  9e-01   1  1  1 | 13  0
 4  -2.607e+03  -3.927e+03  +3e+02  5e-01  1e+00  3e+00  2e-01  0.5013  4e-01   2  2  2 |  4  3
 5  -1.509e+03  -2.754e+03  +2e+02  6e-01  1e+00  3e+00  1e-01  0.9791  7e-01   2  1  1 |  8  0
 6  -9.519e+02  -2.124e+03  +1e+02  6e-01  1e+00  4e+00  9e-02  0.5013  5e-01   1  1  1 |  5  3
 7  -1.844e+02  -1.298e+03  +1e+02  7e-01  1e+00  4e+00  6e-02  0.9791  7e-01   1  1  1 |  9  0
 8  +5.633e+02  -4.940e+02  +8e+01  6e-01  9e-01  4e+00  5e-02  0.2479  2e-01   1  1  1 |  2  6
 9  +6.198e+02  -4.340e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0220  3e-01   2  1  1 |  3 17
10  +6.217e+02  -4.319e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0008  3e-01   1  1  1 |  3 32
11  +6.222e+02  -4.315e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0002  3e-01   2  1  1 |  3 39
12  +6.222e+02  -4.314e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0000  3e-01   1  1  1 |  3 51
13  +6.222e+02  -4.314e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0000  3e-01   1  1  1 |  3 64
14  +6.222e+02  -4.314e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0000  3e-01   1  1  1 |  3 75
15  +6.222e+02  -4.314e+02  +8e+01  6e-01  9e-01  5e+00  5e-02  0.0000  3e-01   1  1  1 |  3 89
Combined backtracking failed 87 0 2 1 sigma 0.261705
Combined line search failed, recovering best iterate (0) and stopping.

NUMERICAL PROBLEMS (reached feastol=1.7e+00, reltol=nan, abstol=1.6e+03).
Runtime: 0.173754 seconds.
```

SCS hits an iteration limit of 100,000 in 70 seconds, pretty far away from the solution,
```
----------------------------------------------------------------------------
	SCS v1.1.5 - Splitting Conic Solver
	(c) Brendan O'Donoghue, Stanford University, 2012
----------------------------------------------------------------------------
Lin-sys: sparse-direct, nnz in A = 3471
eps = 1.00e-04, alpha = 1.80, max_iters = 100000, normalize = 1, scale = 5.00
Variables n = 309, constraints m = 1644
Cones:	primal zero / dual free vars: 21
	linear vars: 1536
	exp vars: 87, dual exp vars: 0
Setup time: 2.70e-03s
----------------------------------------------------------------------------
 Iter | pri res | dua res | rel gap | pri obj | dua obj | kap/tau | time (s)
----------------------------------------------------------------------------
...
 99000| 1.77e-01  5.12e-04  5.03e-07  2.51e+05  2.51e+05  0.00e+00  7.11e+01 
 99100| 1.74e-01  6.82e-03  5.59e-07  2.51e+05  2.51e+05  0.00e+00  7.12e+01 
 99200| 1.76e-01  2.33e-03  4.92e-07  2.51e+05  2.51e+05  0.00e+00  7.12e+01 
 99300| 1.76e-01  3.02e-03  5.20e-07  2.51e+05  2.51e+05  0.00e+00  7.13e+01 
 99400| 1.75e-01  1.31e-03  5.19e-07  2.51e+05  2.51e+05  0.00e+00  7.14e+01 
 99500| 1.75e-01  1.62e-03  5.08e-07  2.51e+05  2.51e+05  0.00e+00  7.15e+01 
 99600| 1.76e-01  2.76e-03  4.98e-07  2.51e+05  2.51e+05  0.00e+00  7.15e+01 
 99700| 1.76e-01  1.65e-03  4.92e-07  2.51e+05  2.51e+05  0.00e+00  7.16e+01 
 99800| 1.75e-01  1.11e-03  5.02e-07  2.51e+05  2.51e+05  0.00e+00  7.17e+01 
 99900| 1.75e-01  2.49e-03  5.13e-07  2.51e+05  2.51e+05  0.00e+00  7.18e+01 
100000| 1.75e-01  1.84e-03  5.24e-07  2.51e+05  2.51e+05  0.00e+00  7.18e+01 
----------------------------------------------------------------------------
Status: Solved/Inaccurate
Hit max_iters, solution may be inaccurate
Timing: Total solve time: 7.18e+01s
	Lin-sys: nnz in L factor: 8418, avg solve time: 6.59e-05s
	Cones: avg projection time: 6.22e-04s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 4.0444e-05, dist(y, K*) = 0.0000e+00, s'y/m = 3.2527e-03
|Ax + s - b|_2 / (1 + |b|_2) = 1.7505e-01
|A'y + c|_2 / (1 + |c|_2) = 1.8444e-03
|c'x + b'y| / (1 + |c'x| + |b'y|) = 5.2448e-07
----------------------------------------------------------------------------
c'x = 251245.7467, -b'y = 251245.4831
============================================================================
```

As I said, this is a pretty easy problem in the nonlinear optimization world. So @emreyamangil and I wrote a [wrapper](https://github.com/mlubin/ConicNonlinearBridge.jl) to let you call Ipopt and other derivative-based NLP solvers from Convex.jl. And it turns out that Ipopt does an okay job on the problem, solving it in a few seconds:

```
 191  7.3494329e+05 1.77e-08 1.13e+02  -8.6 2.73e-04    -  1.00e+00 1.73e-01h  1
 192  7.3494329e+05 1.01e-08 5.27e-10  -8.6 2.91e-04    -  1.00e+00 1.00e+00h  1
 193  7.3494329e+05 7.29e-09 5.74e-09  -9.0 5.74e-05  -4.0 1.00e+00 1.00e+00h  1

Number of Iterations....: 193

                                   (scaled)                 (unscaled)
Objective...............:   7.3494328523825947e+05    7.3494328523825947e+05
Dual infeasibility......:   5.7405480369254747e-09    5.7405480369254747e-09
Constraint violation....:   7.2910966153472145e-09    7.2910966153472145e-09
Complementarity.........:   1.1161736857597210e-09    1.1161736857597210e-09
Overall NLP error.......:   7.2910966153472145e-09    7.2910966153472145e-09

Number of objective function evaluations             = 208
Number of objective gradient evaluations             = 194
Number of equality constraint evaluations            = 208
Number of inequality constraint evaluations          = 208
Number of equality constraint Jacobian evaluations   = 194
Number of inequality constraint Jacobian evaluations = 194
Number of Lagrangian Hessian evaluations             = 193
Total CPU secs in IPOPT (w/o function evaluations)   =      3.416
Total CPU secs in NLP function evaluations           =      0.040
```

I'm optimistic about the conic solvers because on other problems they do just fine and ECOS typically converges faster and in fewer iterations than Ipopt when it works. The ability to mix SOC and exponential cones and get more reliable infeasibility and unboundedness detection is also a big advantage for the conic solvers. But for the moment I have to stick to Ipopt for instances like these since it's the only solver that works. What are the next steps in pushing forward to more reliable exponential cone solvers?

@tiagoakle mentioned the precision of the linear solves in ECOS as an issue. Is that the main problem? Ipopt likely has some tricks, though it's just using MUMPS 4.10 which is is not state of the art.

CC @tiagoakle @poulson @echu @adomahidi @bodono @mcg1969
@IainNZ @joehuchette

**Comment by mlubin** [comment]
CC @SteveDiamond

**Comment by mcg1969** [comment]
I don't think ECOS is the first such solver, but it is certainly the first one widely available. And there is a good reason for that---nonsymmetric cones pose challenges for long-step algorithms. There is really going to be no substitute for bug reports and test problems to shake out the convergence issues; and it is, unfortunately, going to be quite likely that performance is going to suffer somewhat to get to a reasonable level of robustness. But I'd be happy with even a factor of 2 in performance loss.

**Comment by mlubin** [comment]
Yes, converging reliably 2x slower than Ipopt is much better than not converging at all.

**Comment by bodono** [comment]
Looking at this again, has it been confirmed that the problem is with the solvers and not the canonicalizer? Multiple solvers, based on different algorithms, failing is sometimes indicative that something has gone wrong with the formulation in my experience.

**Comment by mlubin** [comment]
@bodono, how would you suggest debugging that? Convex.jl produces an exponential cone problem which is large but not too difficult to inspect. Note that the in the example above, Ipopt takes in the exact same formulation as the conic solvers and is able to solve the problem easily.

**Comment by bodono** [comment]
If it takes in the exact same formulation then that would suggest a problem in ECOS and SCS. But I'm guessing there is some difference in the data that gets passed to the solvers at the final layer, since even the ECOS and SCS APIs are different. An easy way to check would be to take the solution from lpopt and make sure that it satisfies the optimality conditions for the ECOS or SCS formulations. One way to do this is to warm-start SCS with the solution (which SCS supports), and it should terminate after the first iteration if the solution is optimal.

**Comment by mlubin** [comment]
@bodono, Ipopt isn't a conic solver, so it's not easy to extract a conic primal-dual solution. I do know that the objective value is correct though.

**Comment by mcg1969** [comment]
I'm afraid I have been too busy serving my corporate masters to look into this.

**Comment by bodono** [comment]
So I take it that it is getting a different problem formulation then?

**Comment by mlubin** [comment]
@bodono, the input is the same. It just translates exponential cone constraints into smooth nonlinear constraints.

**Comment by bodono** [comment]
The same as what? ECOS and SCS have different APIs.

**Comment by mlubin** [comment]
The same in [MathProgBase conic format](http://mathprogbasejl.readthedocs.org/en/latest/conic.html)

**Comment by bodono** [comment]
Ok, so there could be a problem converting from that format into the specific ECOS and SCS formats.

**Comment by mlubin** [comment]
Definitely possible, although that code path is reasonably well tested.

**Comment by bodono** [comment]
Maybe try a smaller example, or test the same problem on ECOS or SCS with cvx / cvxpy?

**Comment by bodono** [comment]
Or is it possible to get lpopt to solve the dual, and them combine them to pass into SCS as a warm-start?

**Comment by mlubin** [comment]
Oh, that's a good idea. I'll give that a shot when I get a chance.

**Comment by mlubin** [comment]
Turned out to be easier to translate the problem into cvxpy. Here's a [gist](https://gist.github.com/mlubin/3bf76dc142460ecb1c4b) with the model and output from SCS, ECOS, and CVXOPT. None of the solvers converge.

**Comment by bodono** [comment]
Ok, thanks for verifying. I will take a look under the hood at what is happening with SCS, maybe I can tweak some parameters to get better performance, but it could be that this is just a hard problem when in conic form.

**Comment by bodono** [comment]
I ran your cvxpy script and got the same results for SCS. However when I increased the 'scale' parameter to 25 it was able to solve it within the max iterations, and could solve it to higher accuracy when I tightened the tolerance too.

The SCS default scale parameter of 1 is clearly not appropriate for this problem. I've been thinking about making the equilibration dynamic, and this is just another piece of evidence that some problems require it.

The call was:
```
result = problem.solve(solver=SCS,verbose=True,max_iters=100000,scale=25)
```
The final output:
```
 23520| 2.65e-04  9.94e-04  1.29e-06  7.34e+05  7.34e+05  3.99e-13  7.05e+00
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 7.05e+00s
	Lin-sys: nnz in L factor: 8368, avg solve time: 3.33e-05s
	Cones: avg projection time: 2.44e-04s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 6.8877e-06, dist(y, K*) = 6.8685e-07, s'y/|s||y| = -7.4797e-10
|Ax + s - b|_2 / (1 + |b|_2) = 2.6515e-04
|A'y + c|_2 / (1 + |c|_2) = 9.9370e-04
|c'x + b'y| / (1 + |c'x| + |b'y|) = 1.2941e-06
----------------------------------------------------------------------------
c'x = 734218.7535, -b'y = 734216.8532
============================================================================
```

And when `eps=1e-4`
```
 37080| 1.14e-05  9.19e-05  1.20e-07  7.35e+05  7.35e+05  4.03e-13  1.10e+01
----------------------------------------------------------------------------
Status: Solved
Timing: Solve time: 1.10e+01s
	Lin-sys: nnz in L factor: 8368, avg solve time: 3.34e-05s
	Cones: avg projection time: 2.40e-04s
----------------------------------------------------------------------------
Error metrics:
dist(s, K) = 9.9888e-06, dist(y, K*) = 6.3609e-07, s'y/|s||y| = 4.2848e-10
|Ax + s - b|_2 / (1 + |b|_2) = 1.1444e-05
|A'y + c|_2 / (1 + |c|_2) = 9.1941e-05
|c'x + b'y| / (1 + |c'x| + |b'y|) = 1.2035e-07
----------------------------------------------------------------------------
c'x = 734922.5230, -b'y = 734922.3461
============================================================================
```

**Comment by mlubin** [comment]
@bodono, thanks for looking into this. Clearly from the perspective of modeling languages we'd prefer for rescaling to be automatic. Do you have any guidance for picking the scale factor in the meantime?

**Comment by mcg1969** [comment]
Agreed. The first priority should be correctness. The documentation can guide people to settings that maximize speed, once their models are yielding good numerical results.

**Comment by bodono** [comment]
Yes, ideally I'd like to abstract this away so the user doesn't even have to know about it.

Typically for the best performance we want the residuals to come down at roughly the same rate. As a heuristic: if the primal residual is slower then I increase the scale, and if the dual is slower then decreasing the scale helps. I have noticed that problems involving the exponential cone often require a higher scale than 1, although that's just an observation. 

How to implement a dynamic scaling procedure is a bit of an open question, but something I want to work on soon.

**Comment by madeleineudell** [comment]
Any objections to closing this issue on exponential cones in Convex.jl?

**Comment by mlubin** [comment]
Not much has been resolved on this front, but agreed that we can close this issue

**Comment by mcg1969** [comment]
Agreed, it's really a solver issue
