### ISSUE TITLE
Logistic_loss function error

### ISSUE THREAD

**Issue by Vgrunert** [JuliaOpt/Convex.jl#113]
Hi,

whenever I try to run the logistic_loss function I get the following error:

ERROR: LoadError: Associative collections only contain Pairs;
Either look for e.g. A=>B instead, or use the `keys` or `values`
function if you are looking for a key or value respectively.

> versioninfo()
> Julia Version 0.4.0-rc1

> Pkg.installed("Convex")
> v"0.0.6"

> Pkg.installed("SCS")
> v"0.0.9"

The example logistic_loss is not reproducible under the given installed versions.

Full Code:

julia> (() -> begin
       # we'll use iris data
       # predict whether the iris species is versicolor using the sepal length and width and petal length and width
       iris = dataset("datasets", "iris")
       ## outcome variable: +1 for versicolor, -1 otherwise
       iris[:Y] = [species == "versicolor" ? 1.0 : -1.0 for species in iris[:Species]]
       Y = array(iris[:Y])
       ## create data matrix with one column for each feature (first column corresponds to offset)
       X = [ones(size(iris, 1)) iris[:SepalLength] iris[:SepalWidth] iris[:PetalLength] iris[:PetalWidth]]
       n, p = size(X)
       beta = Variable(p)
       problem = minimize(logistic_loss(-Y.*(X*beta)))
       solve!(problem, SCSSolver(verbose=false))
       end)()
WARNING: array(da::DataArray{T}) is deprecated.
Use convert(Array, da).
 in depwarn at ./deprecated.jl:73
 in array at /home/vincent/.julia/v0.4/DataArrays/src/deprecated.jl:23
 in anonymous at none:7
while loading no file, in expression starting on line 0
ERROR: Associative collections only contain Pairs;
Either look for e.g. A=>B instead, or use the `keys` or `values`
function if you are looking for a key or value respectively.
 in in at dict.jl:13
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/stack.jl:53
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/transpose.jl:44
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:106
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/index.jl:70
 in conic_form! at /home/.../.julia/v0.4/Convex/src/constraints/exp_constraints.jl:54
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/exp_cone/exp.jl:51
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/sum.jl:48
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/exp_cone/logsumexp.jl:51
 in conic_form! at /home/.../.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:106
 in conic_form! at /home/.../.julia/v0.4/Convex/src/constraints/constraints.jl:40
 in conic_form! at /home/.../.julia/v0.4/Convex/src/problems.jl:96
 in conic_problem at /home/.../.julia/v0.4/Convex/src/problems.jl:111
 in solve! at /home/.../.julia/v0.4/Convex/src/solution.jl:32
 in anonymous at none:13

**Comment by mlubin** [comment]
The released version of convex.jl is not compatible with julia 0.4. Try ``Pkg.checkout("Convex")``.

**Comment by Vgrunert** [comment]
julia> Pkg.checkout("Convex")
INFO: Checking out Convex master...
INFO: Pulling Convex latest master...
INFO: No packages to install, update or remove

**Comment by Vgrunert** [comment]
Well, anyway. That error pops up under the given versions.

**Comment by mlubin** [comment]
Restart julia and try it again

**Comment by Vgrunert** [comment]
Thanks. Problem solved.
