### ISSUE TITLE
"/" operator implementation

### ISSUE THREAD

**Issue by Vgrunert** [JuliaOpt/Convex.jl#114]
Hi,

I've been been wondering if there it would be possible to implement the "/" operator for dividing of something like:

data = rand(10)
a = Variable(1)
p = maximize( -sum(data) / a )
solve!(p)

The fact that it is not possible to divide by a Convex.Variable rules out most density/likelihood estimation. 

I also tried:

p = maximize( -sum(data) * a^-1. 

which does not work either.

**Comment by mlubin** [comment]
``1/x`` is only convex when ``x > 0``. See the ``inv_pos`` operation in the docs.

**Comment by Vgrunert** [comment]
(()->begin
       A = [ones(10) rand(10,3)]
       x_ = [12,2.4,3.9,44]
       y = A * x_ + rand(Normal(), 10)
       x = Variable(4)
       s = Variable(1)
       p = maximize( -invpos(s) * sumsquares(y-A*x) )
       p.constraints += s > 0
       solve!( p, SCSSolver(verbose=0) )
       print([x.value])
       end)()
WARNING: Expression not DCP compliant. Trying to solve non-DCP compliant problems can lead to unexpected behavior.
WARNING: Problem not DCP compliant: objective is not DCP
ERROR: multiplication of two non-constant expressions is not DCP compliant
 in conic_form! at /home/vincent/.julia/v0.4/Convex/src/atoms/affine/multiply_divide.jl:69
 in conic_form! at /home/vincent/.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:107
 in conic_form! at /home/vincent/.julia/v0.4/Convex/src/constraints/constraints.jl:41
 in conic_form! at /home/vincent/.julia/v0.4/Convex/src/problems.jl:90
 in conic_problem at /home/vincent/.julia/v0.4/Convex/src/problems.jl:105
 in solve! at /home/vincent/.julia/v0.4/Convex/src/solution.jl:23
 in solve! at /home/vincent/.julia/v0.4/Convex/src/solution.jl:13

**Comment by mlubin** [comment]
No it shouldn't, that's not DCP compliant as the output states. When interacting with Convex.jl (like CVX and cvxpy), it's the user's job to formulate your problem in DCP-compatible format. These systems are simpler than you might think; they can only detect convexity if you follow the modeling rules. For the above case, look at the ``quad_over_lin`` operation.

**Comment by Vgrunert** [comment]
Alright. Thank you for the response.
