### ISSUE TITLE
Geometric Programming situation?

### ISSUE THREAD

**Issue by MatthiasKauer** [JuliaOpt/Convex.jl#124]
Hi,
I'm wondering if Convex.jl supports geometric programming.
I have toyed around a bit and tried something in the docs, but I have to admit I'm a beginner with Julia.
In https://github.com/JuliaOpt/Convex.jl/issues/51 from Aug 2015, a poster mentions that geometric programs cannot be parsed automatically, but they can be converted manually. I'm aware of the corresponding method in the GP tutorial paper.

Is this still the current situation? Are there plans to support Geometric Programming directly? If I go the manual route, what are my solver options? If I remember correctly, the manual conversion ends up with a convex but nonlinear formulation. Does that mean all solvers under NLP on http://www.juliaopt.org/ are usable?

Kind regards,
Matthias

**Comment by mlubin** [comment]
There's still no specialized support for modeling or solving geometric programming problems. Support for problem classes by these is driven by necessity, and so far none of the JuliaOpt devs have needed to solve GPs for their own work, though that could change. Contributions are welcome of course.

If you manually reformulate the GP into convex form, you can go ahead and use any of the NLP solvers or exponential cone solvers like ECOS or SCS, but I wouldn't recommend going this route unless you know the GPs are relatively small. You should look into using a specialized GP solver like [Mosek](https://github.com/JuliaOpt/Mosek.jl/issues/28). [gpkit](https://github.com/hoburg/gpkit) is a good solution for modeling GPs in python.

**Comment by MatthiasKauer** [comment]
Thank you for the excellent explanation!
I take it then that the GP mode in cvx for MATLAB does a bit more than just converting to the exponential/logarithmic representation to achieve the higher performance. Is that right?
The GP tutorial and the chapter in the convex optimization book do not seem to mention additional details.

Big thanks also for hinting at gpkit!

**Comment by mlubin** [comment]
> I take it then that the GP mode in cvx for MATLAB does a bit more than just converting to the exponential/logarithmic representation to achieve the higher performance. Is that right?

Actually no, GPs in CVX are slow according to their [documentation](http://cvxr.com/cvx/doc/gp.html):

> The solvers used in this version of CVX do not support geometric programming natively. Instead, they are solved using the successive approximation technique described in The successive approximation method. This means that solving GPs can be slow, but for small and medium sized problems, the method works well.

**Comment by mlubin** [comment]
This is pre-alpha code (written today), but if you'd like to take a look we have a prototype JuMP extension for GP: https://github.com/mlubin/JuGP.jl

**Comment by madeleineudell** [comment]
Cool!

On Sun, Mar 6, 2016 at 2:02 PM, Miles Lubin <notifications@github.com>
wrote:

> This is pre-alpha code (written today), but if you'd like to take a look
> we have a prototype JuMP extension for GP:
> https://github.com/mlubin/JuGP.jl
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/124#issuecomment-193005076>.
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by MatthiasKauer** [comment]
very cool indeed :)
This might be enough to fuel my little project and justify further Julia investigation on my part.
