### ISSUE TITLE
UndefRefError if the solver doesn't populate the solution after crash / infeasible / unbounded

### ISSUE THREAD

**Issue by emreyamangil** [JuliaOpt/Convex.jl#130]
This is coming from src/solution.jl (populate_solution!). Maybe query the solution only if optimal?? Thanks!

@mlubin

**Comment by madeleineudell** [comment]
We've implemented it this way because frequently solutions are quite good even if the solver doesn't think so - this happens often with SCS. Would a try / catch around populating the solution do the trick here?

**Comment by emreyamangil** [comment]
Thanks @madeleineudell ! From what I see the issue might be the Solution query at the catch portion? (line 105) Maybe having a separate try and catch for duals and solution might help (with catches filling NaN).

**Comment by madeleineudell** [comment]
Sounds fine to me. Would you make a PR?

On Fri, Apr 1, 2016 at 9:32 PM, Emre Yamangil <notifications@github.com>
wrote:

> Thanks @madeleineudell <https://github.com/madeleineudell> ! From what I
> see the issue might be the Solution query at the catch portion? (line 105)
> Maybe having a separate try and catch for duals and solution might help
> (with catches filling NaN).
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/130#issuecomment-204642632>
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by emreyamangil** [comment]
Will do!
