### ISSUE TITLE
add det_rootn atom

### ISSUE THREAD

**Issue by chriscoey** [JuliaOpt/Convex.jl#132]
CVX has it. According to https://github.com/cvxr/CVX/blob/master/functions/det_rootn.m

> This function can be used in many convex optimization problems that call for
> LOG(DET(X)) instead. For example, if the objective function contains nothing
> but LOG(DET(X)), it can be replaced with DET_ROOTN(X), and the same optimal 
> point will be produced.

**Comment by madeleineudell** [comment]
Have you tried the logdet atom?

**Comment by chriscoey** [comment]
Thanks Madeleine. I'm a bit of a noob but my understanding is that logdet requires a solver that will deal with the expo cone (so I can't use say MOSEK), but det_rootn avoids this. Is that correct?

At the moment I'm ok with logdet because I am using SCS, but I'd like to be able to use a more powerful SDP solver.

**Comment by madeleineudell** [comment]
I see! det_rootn computes the nth root of the determinant of a matrix X,
which can be computed using geo_mean(eig(X)). I don't this this currently
would work in Convex (we have an experimental eig implementation, but it is
not exported), but it wouldn't be too hard to add. Why don't you create an
issue for this?

On Sat, Mar 26, 2016 at 9:28 PM, Chris C. <notifications@github.com> wrote:

> Thanks Madeleine. I'm a bit of a noob but my understanding is that logdet
> requires a solver that will deal with the expo cone (so I can't use say
> MOSEK), but det_rootn avoids this. Is that correct?
>
> At the moment I'm ok with logdet because I am using SCS, but I'd like to
> be able to use a more powerful SDP solver.
>
> —
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/132#issuecomment-201988931>
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115

**Comment by chriscoey** [comment]
Oh great! Is the eig implementation on someone's branch? It might be useful for some things that @mlubin and I are looking at currently. 

In the meantime, I will submit an issue for geo_mean(eig(X)). Thanks!

**Comment by chriscoey** [comment]
See #134
