### ISSUE TITLE
Error using fixed variables as parameters

### ISSUE THREAD

**Issue by nxtruong** [JuliaOpt/Convex.jl#139]
This error happened on both the registered version (0.2.0) and the latest (master branch).

I'm solving a problem where the cost function has the form: `quadform(x,P) + delta'*x`, in which delta is defined as a vector variable but in fact is a vector parameter that will be fixed before solving the problem (I'm following http://convexjl.readthedocs.io/en/latest/advanced.html).

In the first try, x was a matrix (`x = Variable(m,n)`) and the x in the cost function was `vec(x)`. This caused the following error when solving the problem (after fixing delta):

> ERROR: type ReshapeAtom has no field value
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/atoms/affine/multiply_divide.jl:90
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:107
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/constraints/constraints.jl:41
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/problems.jl:90
>  in conic_problem at /Users/truong/.julia/v0.4/Convex/src/problems.jl:105
>  in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:23

It seemed to me that line 90 of multiply_divide.jl accesses field "value" of vec(x) which doesn't exist.
So I tried to define x as a vector (`x = Variable(m*n)`). This time, the same line caused a different error:

> ERROR: MethodError: `kron` has no method matching kron(::Void, ::SparseMatrixCSC{Float64,Int64})
> Closest candidates are:
>   kron(::Any, ::Any, ::Any, ::Any...)
>   kron{Tv,Ti}(::SparseMatrixCSC{Tv,Ti}, ::SparseMatrixCSC{Tv,Ti})
>   kron{Tv1,Ti1,Tv2,Ti2}(::SparseMatrixCSC{Tv1,Ti1}, ::SparseMatrixCSC{Tv2,Ti2})
>   ...
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/atoms/affine/multiply_divide.jl:90
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:107
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/constraints/constraints.jl:41
>  in conic_form! at /Users/truong/.julia/v0.4/Convex/src/problems.jl:90
>  in conic_problem at /Users/truong/.julia/v0.4/Convex/src/problems.jl:105
>  in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:25
>  in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:13

This time I don't understand why the field "value" returned Void.

**Comment by madeleineudell** [comment]
Hi Truong,

Can you please send the full code you're using that throws these errors?

It sounds like the problem might just be a user interface problem: when you
solve the problem, you will have assigned a value to the parameter delta;
but perhaps you're forming the problem before doing that. If you send me
the code I can see whether I can change the interface to make it more
straightforward to interact with the code.

Madeleine

On Sun, May 22, 2016 at 5:23 AM, Truong X. Nghiem <notifications@github.com>
wrote:

> This error happened on both the registered version (0.2.0) and the latest
> (master branch).
>
> I'm solving a problem where the cost function has the form: quadform(x,P)
> + delta'*x, in which delta is defined as a vector variable but in fact is
> a vector parameter that will be fixed before solving the problem (I'm
> following http://convexjl.readthedocs.io/en/latest/advanced.html).
>
> In the first try, x was a matrix (x = Variable(m,n)) and the x in the
> cost function was vec(x). This caused the following error when solving
> the problem (after fixing delta):
>
> ERROR: type ReshapeAtom has no field value
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/atoms/affine/multiply_divide.jl:90
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:107
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/constraints/constraints.jl:41
> in conic_form! at /Users/truong/.julia/v0.4/Convex/src/problems.jl:90
> in conic_problem at /Users/truong/.julia/v0.4/Convex/src/problems.jl:105
> in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:23
>
> It seemed to me that line 90 of multiply_divide.jl accesses field "value"
> of vec(x) which doesn't exist.
> So I tried to define x as a vector (x = Variable(m*n)). This time, the
> same line caused a different error:
>
> ERROR: MethodError: kron has no method matching kron(::Void,
> ::SparseMatrixCSC{Float64,Int64})
> Closest candidates are:
> kron(::Any, ::Any, ::Any, ::Any...)
> kron{Tv,Ti}(::SparseMatrixCSC{Tv,Ti}, ::SparseMatrixCSC{Tv,Ti})
> kron{Tv1,Ti1,Tv2,Ti2}(::SparseMatrixCSC{Tv1,Ti1},
> ::SparseMatrixCSC{Tv2,Ti2})
> ...
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/atoms/affine/multiply_divide.jl:90
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/atoms/affine/add_subtract.jl:107
> in conic_form! at
> /Users/truong/.julia/v0.4/Convex/src/constraints/constraints.jl:41
> in conic_form! at /Users/truong/.julia/v0.4/Convex/src/problems.jl:90
> in conic_problem at /Users/truong/.julia/v0.4/Convex/src/problems.jl:105
> in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:25
> in solve! at /Users/truong/.julia/v0.4/Convex/src/solution.jl:13
>
> This time I don't understand why the field "value" returned Void.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/139>
>



-- 
Madeleine Udell
Postdoctoral Fellow at the Center for the Mathematics of Information
California Institute of Technology
*https://courses2.cit.cornell.edu/mru8
<https://courses2.cit.cornell.edu/mru8>*
(415) 729-4115
