### ISSUE TITLE
problem with test - fix multiplication

### ISSUE THREAD

**Issue by gabgoh** [JuliaOpt/Convex.jl#142]
The following test seems to be flawed

``` julia
set_default_solver(SCSSolver(eps = 1e-20))

a = [1,2,3,2,1]
x = Variable(length(a))
gamma = Variable(Positive())
fix!(gamma, 1)

p = minimize(norm(x-a) + gamma*norm(x[1:end-1] - x[2:end]))
solve!(p)
o1 = p.optval

# increase regularization
fix!(gamma, 3)
solve!(p)
o2 = p.optval
```

When I call o1 - o2

``` julia
julia> o1 - o2
-4.9320547645947954e-12
```

The objective values seem to be either identical or too close for this to be passed by most reasonable solvers.

**Comment by mlubin** [comment]
@gabgoh, I suspect a PR fixing this would be welcome

**Comment by ericphanson** [comment]
This was fixed in https://github.com/JuliaOpt/Convex.jl/commit/8f4aa2b56658487998f0a510335470893dce5108
