### ISSUE TITLE
lambdamax and lambdamin need positive semidefinite argument?

### ISSUE THREAD

**Issue by moehle** [JuliaOpt/Convex.jl#152]
It appears that lambdamax and lambdamin both require a positive semidefinite argument, which seems unnecessary.  Is there any reason for this?  It seems if I were to modify conic_forms! for LambdaMaxAtom, for example, all I need to do is remove the A >= 0 constraint, and it will work.  Am I missing something?

**Comment by Ayush-iitkgp** [comment]
Hi @moehle, from my limited understanding of [Disciplined Convex Programming](http://dcp.stanford.edu/) and Convex.jl, we only deal with the expressions which are DCP compliant. If you remove the constraint that A is positive semidefinite matrix then variable x no longer remain in SDP cone which violates the rules of DCP compliant and Convex.jl only solves DCP compliant problems.

Hope I am making sense.

**Comment by madeleineudell** [comment]
@moehle, I believe you've caught a bug! It should be fixed shortly.

@Ayush-iitkgp, the problem 
```
A = Variable(n,n)
minimize(t, t*eye(n) - A in :SDP)
```
is a perfectly well posed disciplined convex program, so @moehle 's question makes sense.
