### ISSUE TITLE
Partial transpose

### ISSUE THREAD

**Issue by peterwittek** [JuliaOpt/Convex.jl#168]
The `HermitianSemidefinite` variable is a phenomenal addition for the quantum information community. It would even be more useful if `kron` was extended to it, and I also wonder if you plan to implement the partial trace and partial transpose functions. Thanks.

**Comment by madeleineudell** [comment]
These functions are not familiar to me, but I'd welcome PRs! Even PRs with
pure documentation: we'd have a much easier time implementing them given a
concise mathematical description of these functions.

On Nov 9, 2016 11:55 AM, "Peter Wittek" <notifications@github.com> wrote:

The HermitianSemidefinite variable is a phenomenal addition for the quantum
information community. It would even be more useful if kron was extended to
it, and I also wonder if you plan to implement the partial trace and
partial transpose functions. Thanks.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/JuliaOpt/Convex.jl/issues/168>, or mute the thread

**Comment by peterwittek** [comment]
Thank you. I just started to pick up Julia, so even the elementary task of writing the pure documentation will take me a while. The kron function would be the same as the basic linear algebra operation [implemented in Julia](http://docs.julialang.org/en/release-0.5/stdlib/linalg/#Base.kron). We implemented the [partial trace](http://picos.zib.de/tools.html#picos.tools.partial_trace) and the [partial transpose](http://picos.zib.de/tools.html#picos.tools.partial_transpose) in [PICOS](http://picos.zib.de/) in Python. I would love to see these functions in Convex.jl, and I will do my best to help in my limited capacity.

**Comment by Ayush-iitkgp** [comment]
Hi @peterwittek thanks for appreciating our work. We implemented the support for complex variables as part of my GSoC'16 project under the mentorship of @madeleineudell and @dvij. Kron and partial trace are in my to-do list too. I am busy looking for a job these days hence can not fulfill your needs immediately but yes certainly in a month or so, I will come back and implement those functions with your help.

**Comment by peterwittek** [comment]
Many thanks, that would be awesome! In that time span, I hope to pick up some Julia skills to be more useful.

**Comment by Ayush-iitkgp** [comment]
Hi @peterwittek are we ready to get going?

**Comment by peterwittek** [comment]
Absolutely. I think the easiest start is the partial transpose. This bit of Python code gives a reference 

```python
import numpy as np
from qutip import partial_transpose, Qobj
rho = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]])
print(Qobj(rho, dims=[[2, 2],[2,2]]))
print(partial_transpose(Qobj(rho, dims=[[2, 2],[2,2]]), [1, 0]))
print(partial_transpose(Qobj(rho, dims=[[2, 2],[2,2]]), [0, 1]))
```

**Comment by peterwittek** [comment]
Actually, I completely missed #57, which has a partial implementation for the tensor product, and  #147, which does the same thing for the partial trace. So here we can focus on the partial transpose. I changed the title of the issue accordingly.

**Comment by Ayush-iitkgp** [comment]
Hi @peterwittek, I went through the [documentation](http://picos.zib.de/tools.html#picos.tools.partial_transpose) at PICOS website. From what I can understand, we first divide the original matrix into submatrices and then take the transpose within the sub-matrices or among the sub-matrices but I am unable to understand the arguments passed to the partial_transpose operator. Can you help me in understanding the arguments? Also, I can imagine this operation on a square matrix whose dimension is a perfect square. Am I right?

**Comment by peterwittek** [comment]
It is a bit more subtle than that. It can be a square matrix of any non-prime dimension. Formally, imagine that you have an n x n matrix A, and an m x m matrix B (real or complex, it does not matter). The Kronecker product A⊗B of these two matrices will be an nm x nm matrix. The partial transpose operator transposes either A or B in the product. So the parameters specify the dimensions of the subsystems (n and m; this can be auto-detected only if the dimension is a square number), and the subsystem you wish to transpose (1 or 2).

Naturally, not all nm x nm matrices factorize as a Kronecker product, but they still have a partial trace. For instance, you can take a Bell pair (using Python and QuTiP):

```python
from qutip import tensor, basis, ket2dm, partial_transpose
psi = (tensor(basis(2, 0), basis(2, 0)) + tensor(basis(2, 1), basis(2, 1))).unit()
rho = ket2dm(psi)
print(partial_transpose(rho, [1, 0]))
print(partial_transpose(rho, [0, 1]))
```

For a system of non-square dimension, you can change the state:

```python
psi = (tensor(basis(2, 0), basis(3, 0)) + tensor(basis(2, 1), basis(3, 1))).unit()
rho = ket2dm(psi)
```

Note that QuTiP keeps track of the dimension of the subsystem, hence it does not have to be specified in the partial trace function.

**Comment by peterwittek** [comment]
I went through the implementation of [partial transpose in QuTiP](https://github.com/qutip/qutip/blob/master/qutip/partial_transpose.py), and that would be test way to follow, as opposed to modifying the `term` function in the partial trace implementation (PR #147). This gives a simple example without involving quantum states:
```python
from qutip import partial_transpose, Qobj
rho = Qobj([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12], [13, 14, 15, 16]],
           dims=[[2, 2], [2, 2]])
print(rho)
print(partial_transpose(rho, [1, 0]))
print(partial_transpose(rho, [0, 1]))
```
The call signature should be identical to partial trace, since we have to tell Convex.jl the dimensions of the subsystems, and the partial transpose atom could do the same checks as that of the partial trace.

**Comment by Ayush-iitkgp** [comment]
@peterwittek as far as I understood, `term` function in PR #147 decomposes the input matrix into it's child matrices whose kron product formed it. If I am right, we would need the `term` function and just modify the line https://github.com/JuliaOpt/Convex.jl/pull/147/files#diff-2da110877b684c8263afb529cd870489R79. Any idea what changes need to be made and how we can do it?

**Comment by Ayush-iitkgp** [comment]
@peterwittek it would be great if you give a test case. I would want to check my implementation against your test case to check the correct of my implementation.

**Comment by peterwittek** [comment]
This would implement the example from the [Peres-Horodecki criterion](https://en.wikipedia.org/wiki/Peres%E2%80%93Horodecki_criterion):
```julia
using Convex
ϕ = [0 0 0 0; 0 0.5 -0.5 0; 0 -0.5 0.5 0; 0 0 0 0]
p = Variable(1)
ρ = p*ϕ+(1-p)*eye(4)/4
constraints = [p >= 0; p <= 1;ρ in :SDP; partialtranspose(ρ, 2, [2; 2])in :SDP]
problem = maximize(p, constraints)
solve!(problem)
```
It should give you 1/3. For the record, here is the Python version:
```python
import numpy as np
import picos
from qutip import tensor, basis, ket2dm, qeye, Qobj

psi = (tensor(basis(2, 0), basis(2, 1)) - tensor(basis(2, 1), basis(2, 0))).unit()
problem = picos.Problem()
p = problem.add_variable('p', lower=0.0, upper=1.0)
rho = p*ket2dm(psi).data.toarray() + (1-p)*np.eye(4)/4
problem.add_constraint(rho>>0)
problem.add_constraint(rho.partial_transpose(dim_1=(2, 2), subsystems=1)>>0)
problem.set_objective('max', p)
solution = problem.solve()
```

**Comment by ericphanson** [comment]
Closed by https://github.com/JuliaOpt/Convex.jl/pull/316
