### ISSUE TITLE
Converting problems to/from CVXPY

### ISSUE THREAD

**Issue by mfalt** [JuliaOpt/Convex.jl#169]
I'm writing a solver to be used with Convex.jl, but many benchmark problems are written for CVXPY. It is relatively tedious to rewrite them to julia. Is there a simple way to convert a problem, either before or after it has been parsed, between CVXPY and Convex.jl?  
If not, does anyone have any recommendations on what level such a conversion would be easiest to write?

**Comment by blegat** [comment]
`Convex.jl` translates the problem into a Conic Model which represents the problem in a format close to the [CBF format used by CBLIB](http://cblib.zib.de/).
I think the easiest way would be to write the problem, after it has been parsed by CVXPY, in the CBF format.
You can then load the problem from the CBF file with `loadproblem!(yoursolver, "yourfile.cbf")`.

**Comment by mlubin** [comment]
I worked on a link with @SteveDiamond from CVXPY into MathProgBase conic from through https://github.com/mlubin/cmpb. So if you write a solver at the level of MathProgBase you're all set.

**Comment by mlubin** [comment]
I'll leave a link here to https://github.com/mlubin/ConicBenchmarkUtilities.jl for posterity.
