### ISSUE TITLE
Problems with workspace()

### ISSUE THREAD

**Issue by gabgoh** [JuliaOpt/Convex.jl#170]
The following code

```
using Convex
x = Variable(1)
prob = minimize(x)

workspace()

using Convex
x = Variable(1)
prob = minimize(x)
```

yields the error
```
ERROR: MethodError: Cannot `convert` an object of type SCS.SCSMathProgModel to an object of type LastMain.MathProgBase.SolverInterface.AbstractConicModel
This may have arisen from a call to the constructor LastMain.MathProgBase.SolverInterface.AbstractConicModel(...),
since type constructors fall back to convert methods.
 in Convex.Problem(::Symbol, ::Convex.Variable, ::Array{Convex.Constraint,1}, ::SCS.SCSSolver) at /Users/gabe/.julia/v0.5/Convex/src/problems.jl:38
 in minimize(::Convex.Variable) at /Users/gabe/.julia/v0.5/Convex/src/problems.jl:165
```

`LastMain` seems to be a backup of the `Main` when `workspace` is invoked. But it seems some of the old types are sticking around? I am not sure.

**Comment by madeleineudell** [comment]
This is a very strange error; I'm not sure how to investigate it. @tkelman any ideas?

**Comment by ararslan** [comment]
The `workspace` function no longer exists as of Julia 0.7, I think partially because there were issues such as this. Since the package now requires 0.7 at a minimum, there is nothing actionable for this issue.
