### ISSUE TITLE
vexity of 1 ./ (1 + sumsquares(x))

### ISSUE THREAD

**Issue by mzaffalon** [JuliaOpt/Convex.jl#208]
`Convex.jl` cannot infer the vexity (concave) of the expression `1 ./ (1 + sumsquares(x))`, which is be the opposite of `1 + sumsquares(x)`

**Comment by madeleineudell** [comment]
That expression is not DCP. To write it in Convex.jl, you'd write `invpos(1+sumsquares(x))`. But `invpos` is convex and *decreasing* and `1+sumsquares(x)` is convex, so convexity of the composite expression cannot be inferred from the composition rules.

**Comment by mzaffalon** [comment]
Silly me, `1 / (1 + x^2)` is neither concave nor convex. Sorry about the noise.
