### ISSUE TITLE
Convex v0.6.0 not registered with METADATA

### ISSUE THREAD

**Issue by omus** [JuliaOpt/Convex.jl#211]
Could you register [Convex.jl v0.6.0](https://github.com/JuliaOpt/Convex.jl/releases/tag/v0.6.0) with METADATA? It looks like Convex.jl v0.5.0  is incompatible with Julia 0.6.

**Comment by omus** [comment]
Since this is already tagged I'm just going to make a METADATA PR.

**Comment by omus** [comment]
It turns out that there was already a PR opened for this: https://github.com/JuliaLang/METADATA.jl/pull/9919

**Comment by iamed2** [comment]
@omus That one is closed now, may want to reopen

**Comment by omus** [comment]
The original PR was closed due to inactivity. Mainly the reason it was never merged was because of:

> I think there was a question about some breaking changes in the tag that never got addressed.

**Comment by Alexander-Barth** [comment]
I run into the same issue that Convex is not updating to v0.6.0. I would assume that now the REQUIRE file includes "julia 0.6" a new release can be made without affecting users on julia 0.5.

**Comment by jzazo** [comment]
Any temporary fix to update Convex.jl to v0.6.0 in julia 0.6? Warning messages are a bit distracting... Thank you.

**Comment by ararslan** [comment]
There is now a v0.7.0 of Convex which supports Julia 0.6 only. As far as I can tell, no action will be taken in regards to v0.6.0 so I'm going to close this. For users on Julia 0.6, I recommend using Convex v0.7.0 now.
