### ISSUE TITLE
vectorized constraint giving `MethodError: no method matchin isless(::Complex{Int64}, ::Int64)`

### ISSUE THREAD

**Issue by jacob-roth** [JuliaOpt/Convex.jl#213]
I'm getting a similar error to #204 when trying to add a vectorized constraint. I'm using Julia v0.6, Convex v0.5.0. Here's my current issue:

```
using Convex
t = Variable(1)
v = Variable(10)
x = Variable(1)
z = rand(100)

problem = minimize(x)
problem.constraints += [t >= 0]

ccc = Convex.MaxAtom[]
for i = 1:10
    c = -(1. + minimum(x.*z))
    cc = t + c
    push!(ccc, max(cc, 0.))
end
problem.constraints += [ccc <= v]
```
but instead of a `Float` error, I'm getting: 

```
MethodError: no method matching isless(::Complex{Int64}, ::Int64)
Closest candidates are:
  isless(::PyCall.PyObject, ::Any) at /Users/jakeroth/.julia/v0.6/PyCall/src/pyoperators.jl:71
  isless(::DataArrays.NAtype, ::Any) at /Users/jakeroth/.julia/v0.6/DataArrays/src/operators.jl:383
  isless(::AbstractFloat, ::Real) at operators.jl:98
```

On the other hand, if I add the constraints with `problem.constraints += [ccc .<= v]`, I get a message saying `Convex` can't convert the elements to constraints:

```
MethodError: Cannot `convert` an object of type Array{Convex.Constraint,1} to an object of type Convex.Constraint
This may have arisen from a call to the constructor Convex.Constraint(...),
since type constructors fall back to convert methods.
```

Is this fixed in a new version? Or what's the proper way to add a vector of constraints? Thanks!

**Comment by madeleineudell** [comment]
Here's the misunderstanding: Convex distinguishes between an array of scalar variables or expressions, and array-shaped variables or expressions. It doesn't know how to compare `ccc` (an array of expressions) with `v` (an array-shaped expression).

Instead, you can use indexing to add each constraint individually:
```
using Convex
t = Variable(1)
v = Variable(10)
x = Variable(1)
z = rand(100)

problem = minimize(x)
problem.constraints += [t >= 0]

for i = 1:10
    c = -(1. + minimum(x.*z))
    cc = t + c
    problem.constraints += max(cc, 0.) <= v[i]
end
```

**Comment by jacob-roth** [comment]
Thanks, I see your point. 

If I were to stick with adding multiple constraints without indexing (i.e., `problem.constraints += [ccc .<= v]`), would adding a new method to the `convert` function be the right approach? I'd like to use this method of adding since I seemed to see performance improvements from adding multiple constraints at once versus adding single constraints individually (and I will be using this for `N`>10).

```
function test1(; N=10000)
    x = Variable(N)
    p = minimize(norm(x))
    for i = 1:N
        z = rand()
        p.constraints += [x[i] >= z]
    end
end

function test2(; N=10000)
    x = Variable(N)
    p = minimize(norm(x))
    z = Vector{Float64}(N)
    for i = 1:N
        zz = rand()
        z[i] = zz
    end
    p.constraints .+= [x .>= z]
end

function test3(; N=10000)
    x = Variable(N)
    p = minimize(norm(x))
    z = Vector{Float64}(N)
    for i = 1:N
        zz = rand()
        z[i] = zz
    end
    p.constraints += [x >= z]
end

@time(test1(N=10000))
@time(test2(N=10000))
@time(test3(N=10000))

>>> 0.457911 seconds (140.03 k allocations: 1.124 GiB, 47.47% gc time)
>>> 0.056281 seconds (70.63 k allocations: 2.625 MiB)
>>> 0.039392 seconds (10.53 k allocations: 819.199 KiB)
```

**Comment by madeleineudell** [comment]
Vectorized syntax will definitely be faster in Convex; so when you can avoid indexing it's best to do so. 

Much of the syntax you proposed above seems very convoluted to me when you can simply write
```
x = Variable(N)
p = minimize(norm(x))
z = rand(N)
p.constraints += x >= z
```

I'm not sure what you're proposing to do using `convert`; do you meant to convert an array to an array-shaped Convex variable? One way to do this is to introduce a new Convex variable of the right size + add a bunch of equality constraints to ensure the new variable has the right values; that will prevent MethodErrors, but won't be any faster than indexing to create the array of constraints directly. Better to create vector-shaped objects in the first place.

**Comment by jacob-roth** [comment]
I agree that syntax of my tests is unnecessarily convoluted on its own. I wouldn't write the problem that way from the outset but formulated my test cases the way I did to try and capture the important parts of my original problem (preallocating memory for one side of my constraint and using a `for` loop).

What I'm hoping to do is find some structure where I can perform element-wise comparisons on the elements of `ccc` (type: `Array{Convex.MaxAtom,1}`, length: 10). I didn't try adding equality constraints and new variables since you said it wouldn't be faster. I tried two other things:

1. I initialized `v = Array{Convex.Variable}(10)` and added the constraint `ccc .<= v`. However, I can't access the elements of `v` and get the following error: `UndefRefError: access to undefined reference`.

2. I initialized `v = Array{Convex.Variable}(10)` and added the constraint with `ccc <= v`. However, I get the following comparison error `MethodError: no method matching isless(::Array{Convex.Variable,1}, ::Array{Convex.MaxAtom,1})`

So maybe `convert` isn't the right approach. Is there somewhere in the source code that you'd suggest I look to try and add this comparison functionality?

**Comment by madeleineudell** [comment]
For your specific example problem you can rewrite it in vectorized syntax:
```
using Convex
t = Variable(1)
v = Variable(10)
x = Variable(1)
z = rand(100)

problem = minimize(x)
problem.constraints += [t >= 0]
problem.constraints += max(-(1. + minimum(x.*z)) + t, 0) <= v
```
This kind of rewriting is often possible.

However, I agree that rewriting in vectorized syntax is not particularly Julian; and I'd love to have a way for Convex to work just as fast with loops and indexing as with vectorized syntax. The problem is that Convex has to create expressions, check convexity, and parse every expression to conic form. If every element in an N-array is an expression, it has to do this N times; whereas if the array is a single expression, it has to do this only once. I think this difficulty is rather fundamental, unless you can figure out how to automatically tell that an array of expressions can be simply rewritten as an array-valued expression. Which should be possible, but I don't know how to do it.

**Comment by jacob-roth** [comment]
Got it, ok, I will try and rewrite my code in a way similar to your suggestion, thanks! I'll post an update later if I get it working!
