### ISSUE TITLE
Do not always display Academic license message

### ISSUE THREAD

**Issue by MFairley** [JuliaOpt/Convex.jl#217]
I'm solving a sequence of models in a for loop and each time I run

`problem = maximize(x)`

I get this message on stdout: "Academic license - for non-commercial use only"

This clouds the console output I am using for debugging. Is there any possibility that this message could be removed or be printed less frequently?

**Comment by mlubin** [comment]
Convex.jl does not print anything about licenses, it's the solver. See the discussion at https://github.com/JuliaOpt/Gurobi.jl/pull/109.
