### ISSUE TITLE
Export name kl_div as an alternative name to the relative_entropy atom

### ISSUE THREAD

**Issue by juliohm** [JuliaOpt/Convex.jl#230]
Most people know this operation by the name of KL-divergence, it would be great to have the name exported and added to the documentation section on supported operations:

```julia
const kl_div = relative_entropy
```

**Comment by juliohm** [comment]
Could you please review this issue?

**Comment by ararslan** [comment]
I'd prefer to add a note to the documentation that it also goes by another name. Generally speaking I don't think aliases for functions are a good idea.

**Comment by juliohm** [comment]
Got it, agree that a place in the documentation would be great.
