### ISSUE TITLE
Inconsistent use of whitespace

### ISSUE THREAD

**Issue by omus** [JuliaOpt/Convex.jl#240]
> 2-space and 4-space indenting seem to be used inconsistently. FWIW I prefer consistent 4-spacing.

_Originally posted by @chriscoey in https://github.com/JuliaOpt/Convex.jl/pull/239#issuecomment-434811074_

**Comment by ararslan** [comment]
There doesn't appear to be a general style guide for JuliaOpt, but [JuMP has its own](http://www.juliaopt.org/JuMP.jl/latest/style.html), which says 4 spaces. It's pretty much the _de facto_ standard anyway.
