### ISSUE TITLE
Convex.jl changes behaviour of vector construction

### ISSUE THREAD

**Issue by pgawron** [JuliaOpt/Convex.jl#241]
I am using Convex.jl from: `https://github.com/invenia/Convex.jl` in Julia 1.0.0.

Expected behaviour:
```julia
julia> [1, 1im]
2-element Array{Complex{Int64},1}:
 1 + 0im
 0 + 1im
```

After importing Convex the construction of vector changes behaviour:
```julia
julia> using Convex

julia> [1, 1im]
2-element Array{Number,1}:
   1    
 0 + 1im
```

**Comment by ararslan** [comment]
Wow, this is really bad. Thanks for the report, I'll get this addressed ASAP.

**Comment by mlubin** [comment]
I think there are some underlying design issues in Convex.jl that make this hard to fix in general. (Sorry, can't point to something more specific without digging into the code again.) Maybe that statement doesn't apply to this specific case though.

**Comment by ararslan** [comment]
In this case it's a fault with #239 in particular; something was overloaded in an unsavory way. It is fixed in https://github.com/invenia/Convex.jl/pull/5.

**Comment by ararslan** [comment]
Fixed on Invenia's master and thus in the PR.
