### ISSUE TITLE
lastindex (end) of Variable of Convex.jl v0.9.0

### ISSUE THREAD

**Issue by utotch** [JuliaOpt/Convex.jl#252]
I have an indexing issue for Variable.
When I use "end" for indexing, it causes Method Error.

```
using Convex
x = Variable(2,3)
x[:,end]
```

MethodError: no method matching lastindex(::Variable, ::Int64)
Closest candidates are:
  lastindex(!Matched::AbstractArray, ::Any) at abstractarray.jl:250
  lastindex(::AbstractExpr) at /opt/share/julia/packages/Convex/Jx4Ka/src/expressions.jl:121

Stacktrace:
 [1] top-level scope at In[5]:3

-- Environment
Convex.jl: v0.9.0

Julia Version 1.0.2
Commit d789231e99 (2018-11-08 20:11 UTC)
Platform Info:
  OS: Linux (x86_64-pc-linux-gnu)
  CPU: Intel(R) Core(TM) i7-6700K CPU @ 4.00GHz
  WORD_SIZE: 64
  LIBM: libopenlibm
  LLVM: libLLVM-6.0.0 (ORCJIT, skylake)
Environment:
  JULIA_DEPOT_PATH = /opt/share/julia

**Comment by ararslan** [comment]
Thanks for the report, looks like when we updated things for Julia 1.0 we didn't get the full upgrade path here. I've fixed it in #253.
