### ISSUE TITLE
Dimension issue in sdp constraint

### ISSUE THREAD

**Issue by osjacky430** [JuliaOpt/Convex.jl#263]
Hi, I'm new to Convex.jl, so maybe it's my problem. However, I can't find the related question on the internet.

So, I'm trying to implement the simulation in the paper, and I encountered the following inequality constraints
![image](https://user-images.githubusercontent.com/11375975/50726600-9cf40280-114a-11e9-897f-297c3dae0791.png)

where Q_i is a n x n matrix, r_i is a n x 1 vector, and s_i - t_i*d_i^2 a scalar, t_i >= 0

In my code, the constraint looks like this (n = 3):

`problem.constraints += (ti ≥ 0);`
`problem.constraints += [Qi + ti * eye  ri; ri'   si - ti * di^2] ⪰ 0;`

I'm expecting the size of constraint to be a 4 x 4. However, the size of the constraint turns out to be 8 x 8

![image](https://user-images.githubusercontent.com/11375975/50726734-3e2f8880-114c-11e9-856d-bf2f3b07cf91.png)

`print(size([Qi + ti * eye  ri; ri'   si - ti * di^2]))` gives me (4, 4).
`print([Qi + ti * eye  ri; ri'   si - ti * di^2] ⪰ 0)` gives me (8, 8).
`print(Qi + ti * eye ⪰ 0)` gives me (3, 3).

Am I misunderstanding something? 

Thanks for anyone's help!

**Comment by ararslan** [comment]
Are _Q_<sub>_i_</sub>, _r_<sub>_i_</sub>, _s_<sub>_i_</sub>, _t_<sub>_i_</sub>, or _d_<sub>_i_</sub> all real or real-valued? If any are complex, the stored value for the constraint _X_ ⪰ 0 is the matrix [ℜ(_X_) -ℑ(_X_); ℑ(_X_) ℜ(_X_)], which will be 8x8 if _X_ is 4x4.

**Comment by osjacky430** [comment]
Ah, I see, so I don't need to decompose the complex matrix to that form on my own. Indeed some of them are composed of complex components, thank you so much!

**Comment by ararslan** [comment]
No problem! The documentation about this could certainly be improved. Improved documentation is on my "hopefully I'll get to it eventually" list.
