### ISSUE TITLE
Bug in kron

### ISSUE THREAD

**Issue by mikolajpp** [JuliaOpt/Convex.jl#267]
The following gives (2,2) dimensional variable
```
z = ComplexVariable(2,2)
kron(z, [1 0;  0 1])
```

Switching the order of the arguments gives the correct (4,4) variable result. 
Unless I am misunderstanding  the meaning of dimensions, the result should be the same in both cases. In either way, both expressions should be multiply-capable with 4x4 matrices.

**Comment by ararslan** [comment]
It could be that `size` is misreporting the size of the operation and that in the end the computation will still be correct, but yeah, either way this does look like a bug.
