### ISSUE TITLE
Running error in Control example

### ISSUE THREAD

**Issue by ryuhhh** [JuliaOpt/Convex.jl#268]
I tried to run Control example, but it does not work. 

The error message said 

>MethodError: no method matching +(::Array{Any,1}, ::EqConstraint)
Closest candidates are:
  +(::Any, ::Any, !Matched::Any, !Matched::Any...) at operators.jl:502
  +(::Array, !Matched::Array...) at arraymath.jl:44
  +(::Array, !Matched::SparseArrays.SparseMatrixCSC) at C:\cygwin\home\Administrator\buildbot\worker\package_win64\build\usr\share\julia\stdlib\v1.0\SparseArrays\src\sparsematrix.jl:1574
  ...
Stacktrace:
 [1] top-level scope at .\In[5]:25

So, I bracketed all the constraints related code. For example

>From
   constraints += position[:, i + 1] == position[:, i] + h * velocity[:, i]
to
  constraints += [ position[:, i + 1] == position[:, i] + h * velocity[:, i] ] 

Then the different error message appeared, like this

>DimensionMismatch("dimensions must match")
Stacktrace:
 [1] promote_shape at .\indices.jl:154 [inlined]
 [2] promote_shape(::Array{Any,1}, ::Array{EqConstraint,1}) at .\indices.jl:145
 [3] +(::Array{Any,1}, ::Array{EqConstraint,1}) at .\arraymath.jl:45
 [4] top-level scope at .\In[6]:25
========================================

I am using Julia 1.0.2.

Is the modifying (adding brackets) appropriate? If it is, what is the problem with the following code?

>using Convex, SCS
#Some constraints on our motion
#The object should start from the origin, and end at rest
initial_velocity = [-20; 100]
final_position = [100; 100]

>T = 100 #The number of timesteps
h = 0.1 #The time between time intervals
mass = 1 #Mass of object
drag = 0.1 #Drag on object
g = [0, -9.8] #Gravity on object

>#Declare the variables we need
position = Variable(2, T)
velocity = Variable(2, T)
force = Variable(2, T - 1)

>#Create a problem instance
mu = 1
constraints = []

>#Add constraints on our variables
for i in 1 : T - 1
  constraints += [ position[:, i + 1] == position[:, i] + h * velocity[:, i] ]
end

>for i in 1 : T - 1
  acceleration = force[:, i]/mass + g - drag * velocity[:, i]
  constraints += [ velocity[:, i + 1] == velocity[:, i] + h * acceleration ]
end

>#Add position constraints
constraints += [ position[:, 1] == 0 ]
constraints += [ position[:, T] == final_position ]

>#Add velocity constraints
constraints += [ velocity[:, 1] == initial_velocity ]
constraints += [ velocity[:, T] == 0 ]

>#Solve the problem
problem = minimize(sumsquares(force), constraints)
solve!(problem, SCSSolver(verbose=0))

**Comment by ararslan** [comment]
The examples haven't been touched or updated in quite a long time, so I'll admit this doesn't really surprise me. #261 should help with this.
