### ISSUE TITLE
Bug in norm/abs

### ISSUE THREAD

**Issue by lpawela** [JuliaOpt/Convex.jl#274]
Consider the following program
```julia
effs = Vector{ComplexF64}[[1/sqrt(2), 0], [1/sqrt(6), 1/sqrt(3)], [(-sqrt(2)-1im*sqrt(6))/(4sqrt(3)), 1/sqrt(3)], [(-sqrt(2)+1im*sqrt(6))/(4sqrt(3)), 1/sqrt(3)]]
effsperm = Vector{ComplexF64}[effs[2], effs[3], effs[4], effs[1]]

X = hcat(effs...)
Y = hcat(effsperm...)

d = size(X, 1)
ρ = ComplexVariable(d, d)
constraints = [ρ in :SDP]
constraints += [tr(ρ)==1]
target = real(norm(diag(X'*ρ*Y), 1))
problem = minimize(target, constraints)
solve!(problem, SCSSolver(verbose=1))
v = problem.optval
```
We get `v=0.660`. Now, lets calculate `sum(abs.(diag(X'*ρ.value*Y)))`. This evaluates to `0.590`. Shouldn't this be equal to `v`?

**Comment by pgawron** [comment]
If we change the line
`target = real(norm(diag(X'*ρ*Y), 1))`
into
`target = real(norm(diag(X'*ρ*conj.(Y)), 1))`
we obtain the expected result.

**Comment by ararslan** [comment]
So the issue is that Convex is conjugating complex values where it shouldn't be?

**Comment by pgawron** [comment]
@ararslan it is not clear where the bug is located, but adding `conj` is a very ugly workaround.

**Comment by lpawela** [comment]
@ararslan it might be a problem with `abs`, as `norm(x, 1)` translates to `sum(abs(x))` in the code. Note that, when I calculate tha value `sum(abs.(diag(X'*ρ.value*Y)))` i have to use `abs.`.

**Comment by ararslan** [comment]
> it might be a problem with `abs`, as `norm(x, 1)` translates to `sum(abs(x))` in the code.

Note that `abs(::AbstractExpr)` "auto-vectorizes," i.e. evaluating the `AbsAtom` actually calls `abs.(x)`. So `norm(x, 1)`/`sum(abs(x))` should evaluate to `sum(abs.(x))`

**Comment by ericphanson** [comment]
I tried figuring out what was going on here, and reduced it down to
```julia
using Convex, SCS, LinearAlgebra

effs = Vector{ComplexF64}[[1/sqrt(2), 0], [1/sqrt(6), 1/sqrt(3)], [(-sqrt(2)-1im*sqrt(6))/(4sqrt(3)), 1/sqrt(3)], [(-sqrt(2)+1im*sqrt(6))/(4sqrt(3)), 1/sqrt(3)]]
effsperm = Vector{ComplexF64}[effs[2], effs[3], effs[4], effs[1]]

X = hcat(effs...)
Y = hcat(effsperm...)

d = size(X, 1)
ρ = ComplexVariable(d, d)

constraints = [ρ== Matrix(1.0*I,d,d)]

target = real((X'*ρ*Y)[7])
problem = minimize(target, constraints)
solve!(problem, SCSSolver(verbose=0))
```
which yields
```julia
julia> problem.optval
0.24999994123636074

julia> real((X'*ρ.value*Y)[7])
0.49999995911540107
```

Likewise, `imag` gives the wrong result (`-0.14433757177308384 ` instead of the correct answer of `-3.075943527663938e-10`). So there must be some bug in `real` and `imag`. The only variable is constrained to be the identity matrix, so there shouldn't be much going on here. But I don't understand how `conic_form!(x::ImaginaryAtom,...)` is supposed to work or what's going wrong. I also tried looking back at some of the previous commits for `real_imag.jl` and I didn't find one that worked successfully on this example.

**Comment by ericphanson** [comment]
Perhaps this is a slightly simpler example:
```julia
using Convex, SCS

a = Complex{Float64}[1.0+2.0im, 1.0+0.0im]
b = Complex{Float64}[2.0+3.0im, 1.0+0.0im]

x = ComplexVariable(2,2)

prob = minimize( real( a' * x * b ))
prob.constraints = [ x == [1.0 0.0; 0.0 1.0] ]

solve!(prob, SCSSolver())
@show prob.optval
@show real( a' * x.value * b)
@show real( a' * b)
```
yields
```julia
prob.optval = -2.9999997043811364
real(a' * x.value * b) = 9.00001101314958
real(a' * b) = 9.0
```
I think the `conic_form!` functions for `real` and `imag` are not handling multiplication correctly (i.e. the real and imaginary parts become intertwined in multiplication via `(x+im*y)*(u+im*v) = (xu - yv) + im*(yu + xv)`, and I think the `conic_form!` functions ignore that).
