### ISSUE TITLE
neg is backwards

### ISSUE THREAD

**Issue by tomerarnon** [JuliaOpt/Convex.jl#276]
Note that `neg`, [as documented](https://convexjl.readthedocs.io/en/latest/operations.html) (and according to its behavior in other versions of CVX) should be convex. In the docs, it says `neg(x) = max(-x, 0)`, and in reality, I believe it's doing `-max(-x, 0)`, and therefore returns ConcaveVexity.
```julia
julia> x = Variable(10);

julia> neg(x)
AbstractExpr with
head: min
size: (10, 1)
sign: Negative()
vexity: ConcaveVexity()
```

**Comment by ararslan** [comment]
Assuming I'm interpreting this correctly, the implementation here (https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/lp_cone/min.jl#L81) is actually doing `neg(x) = min(x, -0)`? 🤔

**Comment by ararslan** [comment]
@iamed2 figured out the -0 bit: It's equivalent to `min(x, 0)` while ensuring that the result is `Negative()`.

**Comment by tomerarnon** [comment]
@ararslan, that's equivalent to `-max(-x, 0)` (I tested it, since reasoning it out was difficult).

**Comment by ararslan** [comment]
Good catch. I guess we should just do what it says on the tin and define it as it's documented. Care to submit a PR for it?

**Comment by iamed2** [comment]
@tomerarnon Where have you seen this defined in other versions of CVX? I was not able to find it in the documentation for the MATLAB version.

**Comment by tomerarnon** [comment]
In [CVX.py](https://www.cvxpy.org/api_reference/cvxpy.atoms.elementwise.html#neg), for example, neg is defined as `-min(x, 0)`, which I think is also equivalent to `max(-x, 0)`.

@ararslan, sure I could submit the one-line pull request.

**Comment by tomerarnon** [comment]
@ararslan, any reason not to just define:
`neg(x::AbstractExpr) = max(-x, 0)`
without the `Constant(...)`
