### ISSUE TITLE
fix! and free! do not work as expected

### ISSUE THREAD

**Issue by boborbt** [JuliaOpt/Convex.jl#298]
I have a sample project in which fix! and free! do not seem to work correctly. In particular, it seems that once fixed variables never change again even after calling free!.

You can get the sample project at: https://pastebin.com/DX1mp5NN

In that sample project I implement the same minimisation problem two times. In the first function I do use the fix! and free! functions to implement an alternating least square approach. 
In the second function I do the same, but avoid the fix! and free! functions and resort to creating new problems where I substitute constants in place of variables that should be fixed.
While I would have expected the two functions to behaves identically, this is not the case. The version without the fix! and free! functions works as expected. The one with fix! and free! does not.

Here you can find the log of the output of the program: https://pastebin.com/fWWmRCFP
(the first 2226 lines are logs of the first function, the following ones are logs of the second function).

Here is an excerpt of the log output for the first few iterations of the implementation using the fix and free functions (α was initialised with value [0.3; 0.7; 1.0]; β was initialised with value [-3.; 3]):

```
┌ Debug: optval (β fixed)
│   p.optval = 103.47459779886627
│   α.value =
│    3×1 Array{Float64,2}:
│     0.0885974060292705
│     ⋮
│   β.value =
│    2-element Array{Float64,1}:
│     -3.0
│      3.0
└ @ Main ~/Research/LIMPET/block-least-squares/issue_example.jl:38
┌ Debug: optval (α fixed)
│   p.optval = 103.47459535939427
│   α.value =
│    3×1 Array{Float64,2}:
│     0.0885974060292705
│     ⋮
│   β.value =
│    2-element Array{Float64,1}:
│     -3.0
│      3.0
└ @ Main ~/Research/LIMPET/block-least-squares/issue_example.jl:44
┌ Debug: optval (β fixed)
│   p.optval = 103.47459779886627
│   α.value =
│    3×1 Array{Float64,2}:
│     0.0885974060292705
│     ⋮
│   β.value =
│    2-element Array{Float64,1}:
│     -3.0
│      3.0
└ @ Main ~/Research/LIMPET/block-least-squares/issue_example.jl:38
```

As you can see the β never changes after initialisation (since it is fixed before having the chance to be optimised in the first iteration), while α changes only the first time. This despite the calls to the free! functions.

Thanks in advance for any help.

**Comment by ericphanson** [comment]
It seems to work on the master branch (you can try this with `] add Convex#master`). Can you confirm?

This would make sense since I fixed some `fix!` and `free!` bugs in https://github.com/JuliaOpt/Convex.jl/pull/294 but a release hasn't been tagged yet.

**Comment by boborbt** [comment]
@ericphanson, I'm happy to confirm that the issue seems fixed when I switch to the master branch.

Thanks for your help!

**Comment by ericphanson** [comment]
Great! Glad to be of help. A release was just tagged, so you shouldn't need the master branch now. Also, beware of calling `fix!` twice in a row without `free!`ing in between (until https://github.com/JuliaOpt/Convex.jl/pull/299 is merged and a release tagged). 

That's all I got with `fix!` and `free!` though, so if you run into any other problems with it, please file an issue. (Post-#299 the `fix!` and `free!` code is fairly simple, so I'm hoping there aren't any more bugs lurking around, but you never know).
