### ISSUE TITLE
`sumlargest` and `sumsmallest` not DCP compliant?

### ISSUE THREAD

**Issue by rofinn** [JuliaOpt/Convex.jl#312]
Are `Convex.sumlargest` and `Convex.sumsmallest` not DCP compliant? I’m getting warnings for a sparsity constraint that looks like `sumlargest(vars, k) >= expected_total * C` where everything apart from `vars` are constant.

**Comment by ericphanson** [comment]
`sumlargest` is convex, so it's only valid in the form `sumlargest(vars, k) <= ...`, and likewise `sumsmallest` is concave, so it can only be used as `sumsmallest(vars, k) >= ...`. Probably the nicest summary of the DCP rules are in the CVX documentation (here's the relevant section for this kind of constraint: http://web.cvxr.com/cvx/doc/basics.html#constraints), but it would be nice if we added a summary of the rules to the docs here too.

**Comment by rofinn** [comment]
Wow, those are nice docs. Thanks!
