### ISSUE TITLE
trace() throws UndefVarError; (not documented) tr() should be used instead

### ISSUE THREAD

**Issue by kmundnic** [JuliaOpt/Convex.jl#319]
I'm using `Convex v0.12.4`. The (stable) docs say that `trace` is implemented, and the examples use `trace`. However, using it throws an error.

The source code suggests that `tr` is implemented instead, in `src/atoms/affine/trace.jl`.

It seems like the documentation needs to include this update.

**Comment by ericphanson** [comment]
Thanks for the report! Agreed

**Comment by RoyiAvital** [comment]
I still don't see any `tr()` or `trace()` in https://jump.dev/Convex.jl/stable/operations/.

**Comment by ericphanson** [comment]
it's [there](https://jump.dev/Convex.jl/stable/operations/#Linear-Program-Representable-Functions), no?
<img width="893" alt="Screenshot 2023-11-25 at 15 13 41" src="https://github.com/jump-dev/Convex.jl/assets/5846501/d5a97abd-2654-40a3-b534-7a9765a3884a">

**Comment by RoyiAvital** [comment]
Silly me, I did a search for `trace` assuming it will be written next to it.
Sorry...
