### ISSUE TITLE
"aux" is not an allowed directory name under windows

### ISSUE THREAD

**Issue by reumle** [JuliaOpt/Convex.jl#349]
and this prevents (obviously) git from creating that directory when cloning your repo. 

In case it would be a very small cost (for you and other users), could you consider amending those names (relevant directories are under docs/examples_literate/…)? In the meantime I'll find a workaround.

Here the reference from 2003.....(other names are also invalid: "con" "prin"..) 
https://coderanch.com/t/131585/engineering/Folder-con-Windows-invalid

**Comment by ericphanson** [comment]
Oops! I had no idea. I'll put up a PR shortly to rename them.

**Comment by reumle** [comment]
Thanks and greetings from happy cloner!
