### ISSUE TITLE
No speedup from multthreading. big speed up from multi-processing

### ISSUE THREAD

**Issue by oxinabox** [JuliaOpt/Convex.jl#370]
It seems like multithreading gives me nothing.
But multiprocessing gives me everything, once it has cached what ever it does on the first run.

This initial example with Convex v0.12.7 and ECOS (will follow up with further investigations on Convex v0.13, with MOI) and other solvers.

```julia
using Distributed
addprocs();

@everywhere using Pkg
@everywhere Pkg.activate(".")
@everywhere using Convex, ECOS
using Base.Threads



@everywhere function trial(ii)
    # Generate random problem data
    m = 40;  n = 50
    A = randn(m, n);
    b = randn(m, 1) .+ ii

    # Create a (column vector) variable of size n x 1.
    x = Variable(n)

    # The problem is to minimize ||Ax - b||^2 subject to x >= 0
    # This can be done by: minimize(objective, constraints)
    problem = minimize(sumsquares(A * x - b), [x >= 0])

    # Solve the problem by calling solve!
    solve!(problem, ECOSSolver(verbose=false); verbose=false)
    
    # Check the status of the problem
    problem.status # :Optimal, :Infeasible, :Unbounded etc.

    # Get the optimal value
    return problem.optval
end

function tmap(f, xs)
    futures = map(xs) do x
        Threads.@spawn f(x)
    end
    return map(fetch, futures)
end

@show nworkers()
@show nthreads()

@time trial(0);
@time trial(0);

@time map(trial, 1:1_000);
@time map(trial, 1:1_000);

@time tmap(trial, 1:1_000);
@time tmap(trial, 1:1_000);

@time pmap(trial, 1:1_000);
@time pmap(trial, 1:1_000);
```

### Results:

```julia
julia> @show nworkers()
nworkers() = 8
8

julia> @show nthreads()
nthreads() = 8
8

julia> @time trial(0);
  7.732639 seconds (24.12 M allocations: 1.161 GiB, 5.92% gc time)

julia> @time trial(0);
  0.004607 seconds (1.89 k allocations: 781.953 KiB)

julia> @time map(trial, 1:1_000);

  4.803069 seconds (2.11 M allocations: 774.855 MiB, 1.51% gc time)

julia> @time map(trial, 1:1_000);

  4.832683 seconds (1.89 M allocations: 763.466 MiB, 1.39% gc time)

julia> @time tmap(trial, 1:1_000);

  1.247847 seconds (2.05 M allocations: 772.096 MiB, 5.85% gc time)

julia> @time tmap(trial, 1:1_000);

  1.143285 seconds (1.90 M allocations: 764.176 MiB, 5.40% gc time)

julia> @time pmap(trial, 1:1_000);

 19.265357 seconds (3.12 M allocations: 157.224 MiB, 0.31% gc time)

julia> @time pmap(trial, 1:1_000);
  1.387546 seconds (65.69 k allocations: 1.917 MiB)
```

**Update:  looks like when I openned this issue I had not set JULIA_NUM_THREADS.
Everything seems fine 😂 **

**Comment by oxinabox** [comment]
### With SCS + Convex 0.12.7

Note this is only running 100 (not 1000) iterations because SCS is 🐌 .

```
julia> @time trial(0);
  8.598299 seconds (27.71 M allocations: 1.342 GiB, 6.09% gc time)

julia> @time trial(0);
  0.018208 seconds (2.10 k allocations: 858.344 KiB)

julia> @time map(trial, 1:100);
 31.543428 seconds (433.40 k allocations: 95.303 MiB, 0.05% gc time)

julia> @time map(trial, 1:100);
 30.326855 seconds (209.51 k allocations: 83.807 MiB, 0.04% gc time)

julia> @time tmap(trial, 1:100);
 32.243065 seconds (368.88 k allocations: 91.994 MiB, 0.03% gc time)

julia> @time tmap(trial, 1:100);
 31.186774 seconds (210.31 k allocations: 83.876 MiB, 0.03% gc time)

julia> @time pmap(trial, 1:100);
 27.587646 seconds (3.06 M allocations: 155.516 MiB, 0.12% gc time)

julia> @time pmap(trial, 1:100);
  7.153105 seconds (6.59 k allocations: 203.531 KiB)
```

So same finding

**Comment by oxinabox** [comment]
With Convex v0.13.0 and ECOS
`solve!(problem, ECOS.Optimizer(verbose=false); verbose=false)`

```
julia> @time trial(0);
 20.021980 seconds (69.36 M allocations: 3.394 GiB, 8.24% gc time)

julia> @time trial(0);
  0.005108 seconds (4.09 k allocations: 1.159 MiB)

julia> @time map(trial, 1:1_000);
  5.723333 seconds (4.18 M allocations: 1.136 GiB, 3.67% gc time)

julia> @time map(trial, 1:1_000);
  5.810455 seconds (4.08 M allocations: 1.132 GiB, 3.36% gc time)

julia> @time tmap(trial, 1:1_000);
  5.612902 seconds (4.24 M allocations: 1.140 GiB, 3.98% gc time)

julia> @time tmap(trial, 1:1_000);
  5.565721 seconds (4.09 M allocations: 1.132 GiB, 3.64% gc time)

julia> @time pmap(trial, 1:1_000);
 49.710265 seconds (3.09 M allocations: 155.504 MiB, 0.05% gc time)

julia> @time pmap(trial, 1:1_000);
  1.332076 seconds (65.65 k allocations: 1.916 MiB)
```

Same as before, but interestingly the initial run time is Way longer.
20s vs 8s

**Comment by oxinabox** [comment]
With Convex v0.13 and COSMO v0.6

```
julia> @show nworkers()
nworkers() = 8
8

julia> @show nthreads()
nthreads() = 8
8

julia> @time trial(0);
 33.068255 seconds (116.64 M allocations: 5.707 GiB, 7.66% gc time)

julia> @time trial(0);
  0.026552 seconds (29.98 k allocations: 2.340 MiB)

julia> @time map(trial, 1:1_000);
 23.890286 seconds (35.49 M allocations: 2.479 GiB, 2.41% gc time)

julia> @time map(trial, 1:1_000);
 24.664103 seconds (34.58 M allocations: 2.438 GiB, 2.32% gc time)

julia> @time tmap(trial, 1:1_000);
  7.727346 seconds (34.75 M allocations: 2.447 GiB, 3.99% gc time)

julia> @time tmap(trial, 1:1_000);
  7.498412 seconds (34.58 M allocations: 2.439 GiB, 7.35% gc time)

julia> @time pmap(trial, 1:1_000);
 93.294722 seconds (3.06 M allocations: 155.061 MiB, 0.10% gc time)

julia> @time pmap(trial, 1:1_000);
  6.288276 seconds (66.09 k allocations: 1.925 MiB)
```

So this looks like `tmap` and `pmap` perform the same

**Comment by oxinabox** [comment]
**looks like when I openned this issue I had not set JULIA_NUM_THREADS.
Everything seems fine 😂 **

**Comment by ericphanson** [comment]
Glad things are ok! Thanks for the benchmarks anyway, it’s interesting to see you get a decent speed up from parallelism— that’s not something I’ve tried before.

By the way, if you’re trying out different solvers, the brand new ConvexTests.jl repo might be of interest (described here: https://discourse.julialang.org/t/ann-convex-0-13-released/35304/2).

**Comment by oxinabox** [comment]
Ok I finally worked out what is going on, 
I think.

Here is my `tmap` from before, and also its new buddy `tmap_warm` which runs the first item unparallelized then runs the rest at the same time.
```julia
function tmap(f, xs)
    futures = map(xs) do x
        Threads.@spawn f(x)
    end
    return map(fetch, futures)
end

function tmap_warm(f, xs)
    x_head, xs_tail = Iterators.peel(xs)
    y1 = f(x_head)
    futures = map(xs_tail) do x
        Threads.@spawn f(x)
    end
    return [y1; map(fetch, futures)]
end
```

Now lets look at some benchmarks.
Back on Convex v0.12

# Exit julia then run no separate `trail` first just straight into:
```
julia> @time tmap(trial, 1:1_000);
 11.840455 seconds (26.18 M allocations: 1.915 GiB, 4.75% gc time)

julia> @time tmap(trial, 1:1_000);
  1.291106 seconds (1.90 M allocations: 764.176 MiB, 5.19% gc time)
```

# Exit julia again then run no seperate `triial` just straight into
```
julia> @time tmap_warm(trial, 1:1_000);
  9.426515 seconds (26.46 M allocations: 1.928 GiB, 6.54% gc time)

julia> @time tmap_warm(trial, 1:1_000);
  1.155993 seconds (1.90 M allocations: 764.192 MiB, 6.94% gc time)
```

So we are looking at the first run after restart:
 - `tmap` gets ~12 sconds
 - `tmap_warm` gets ~9 seconds

This does not seem like much. And just looking at the MWE i thought it might be down to chance.

But then I ran my real problem.
  - `tmap` ~60 seconds
 - `tmap_warm` ~20 seconds

Great victory.

My theory:  somewhere in Convex / ECOS
it caches these intermediary values that represent how to handle a certain kind of transform that you do in the process of solving a particular type of convex optimisation problem.
or a particular pattern of constraints and objective parts

And working that out is by far the most expensive part of solving the problem. (Noting how between the two calls to `trial`  first solve took ~8s and second solve took ~0.005s)
And the issue we were running into was that because all the threads were hitting it at roughly the same time, they were all like “No transform has been computed for this. I guess I better work one out”
so by running the first solve on its own, we make sure that transform is computed at the start. So then when we start up all the other solves it is ready for them.

Does my theory make sense?

Not sure if there is a way to generalize avoiding the senario into Convex itself.
But it seems like a thing to watch out for.

**Comment by oxinabox** [comment]
But that doesn't fully explain it for my real case.
Since why 60 seconds not 40 seconds?
20s + 20s which would be worst case if it was almost able to it but had to solve seperately.
It must be something to do with some internal thread safety since I was told `pmap` does not do this on my-non-MWE. (and thats why I was looking at this code in the first place.)
(though it kind of looks like `pmap` does do this on the MWEs posted above)

**Comment by ericphanson** [comment]
I don’t think Convex.jl does any caching between problems (https://github.com/JuliaOpt/Convex.jl/pull/343)  or even between separate solves of the same problem (https://github.com/JuliaOpt/Convex.jl/issues/318). The caching Convex does is within a single solve of a single problem, any identical expressions have their conic forms cached and only need to be computed once). No idea about ECOS though, or MathProgBase (which Convex sends the problem to, on its way to ECOS).

Could there be a compilation bottleneck? I don’t know at all how compilation works with multiple threads, but maybe the separate first solve lets all threads access the compiled version without contention or something?

**Comment by oxinabox** [comment]
Hmmmm compilation was my first guess. But it's so long. But maybe.
I will do more experiments.

**Comment by ericphanson** [comment]
I'm not sure; on Convex 0.13 it would make more sense to me because there's all kinds of layers and bridges and things in MOI that get compiled away and depend on the problem (because what bridges you need depends on the problem + what the solver can handle). With <0.13 it's more surprising and usually Convex + MPB seemed fairly light on compilation.

Is the real case still with 8 threads, or way more? Maybe the contention scales with # of threads.

**Comment by oxinabox** [comment]
Real case, with 8 cores.
(Its actually still not the real real case, but a scaled down version.

### `tmap`
51.249667 seconds (82.40 M allocations: 4.306 GiB, 1.83% gc time)

### `tmap_warm`
20.535359 seconds (66.68 M allocations: 3.423 GiB, 3.92% gc time)

### `tmap` with seperate small solve at start to make sure convex etc is all compiled
48.173632 seconds (75.19 M allocations: 3.957 GiB, 1.53% gc time)

Note this does not rule out issues with compile time of some of the other code called inside the tmap loop.
Which is not a particularly small amount of code.

---

In all cases the time to run it a second time is < 1s.

I also tried using `map` instead of `tmap` and that also takes about 20s the first time.
But with that the second time is like 3s.
(and because this is a scaled down version of the real real problem, that tells me that single threading is not going to scale)
