### ISSUE TITLE
current status

### ISSUE THREAD

**Issue by xin-jin** [JuliaOpt/Convex.jl#44]
Hi, just a quick question. Is this package stable and usable as the matlab cvx? I took 364a quite a while ago and it was taught using cvx. But peronsally I don't use matlab for my daily task. For computations I mainly use python and recently switched to julia. So just wondering if it is able to replace cvx (so that I can uninstall and forget matlab)?

**Comment by madeleineudell** [comment]
Yes, this package should be approximately as stable and usable as cvx in
matlab. We don't have quite as many atoms as cvx, but we're adding them
rapidly and happy to take feature requests.

On Sun, Jan 4, 2015 at 12:53 AM, xin-jin <notifications@github.com> wrote:

> Hi, just a quick question. Is this package stable and usable as the matlab
> cvx? I took 364a quite a while ago and it was taught using cvx. But
> peronsally I don't use matlab for my daily task. For computations I mainly
> use python and recently switched to julia. So just wondering if it is able
> to replace cvx?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/cvxgrp/Convex.jl/issues/44>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell
