### ISSUE TITLE
Finish migration to JuliaOpt

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/Convex.jl#48]
Clean up the trailing links: 

- [x] travis
- [x] coveralls
- [x] readthedocs
- [ ] juliacon
- [ ] john miles white

then:

- [x] annouce on julia-users
- [ ] announce on julia-opt

(Joey: edited for checkboxes)

**Comment by joehuchette** [comment]
:tada:

**Comment by joehuchette** [comment]
What needs to be done w.r.t. Juliacon? I couldn't find a direct link to the repo anywhere on the site, just the video of your talk.

**Comment by joehuchette** [comment]
The link on @johnmyleswhite blog redirects to the repo after the the move, though we could ask him to point it to the URL (and change CVX --> Convex)

**Comment by karanveerm** [comment]
https://travis-ci.org/JuliaOpt/Convex.jl/builds
https://coveralls.io/r/JuliaOpt/Convex.jl
https://readthedocs.org/projects/convexjl/ 
(I'll need readthedocs usernames of JuliaOpt people if you want me to give you access to it)

As Joey said, JuliaCon and other stuff redirect to this repo, so it doesn't matter too much.

**Comment by mlubin** [comment]
:100: 
My RTD username is mlubin.

**Comment by mlubin** [comment]
For SEO it could be better to have all the links up to date even if they redirect.

**Comment by mlubin** [comment]
Ping @johnmyleswhite, could you update the link to CVX.jl at http://www.johnmyleswhite.com/notebook/2014/06/30/my-experience-at-juliacon/?

**Comment by mlubin** [comment]
@madeleineudell, no need to hold off on the announcement at this point.
