### ISSUE TITLE
Segmentation fault: 11

### ISSUE THREAD

**Issue by daisy12321** [JuliaOpt/Convex.jl#51]
Hi there,

I am using a variation of the example logistic regression code with Convex.jl. The code seems to work for the first time I run in Julia, but if I try running the exact same code again in the Julia kernel, the terminal would quit out of Julia with a segmentation fault as below: 

```
signal (11): Segmentation fault: 11
broadcast! at broadcast.jl:220
broadcast at broadcast.jl:234
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
+ at /Users/zhuo/.julia/v0.3/Convex/src/conic_form.jl:26
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:110
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:79
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/exp_cone/logsumexp.jl:52
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:46
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:36
conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:60
conic_problem at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:72
solve! at /Users/zhuo/.julia/v0.3/Convex/src/solution.jl:13
julia_solve!;20593 at  (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
solve_convex at /Users/zhuo/documents/Julia/logit_func.jl:43
jlcall___solve_convex#175__;21122 at  (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/gf.c:1416
julia_solve_convex;21121 at  (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/interpreter.c:59
eval at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/interpreter.c:207
jl_toplevel_eval_flex at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/toplevel.c:494
jl_parse_eval_all at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/toplevel.c:542
jl_load at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/toplevel.c:579
include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/interpreter.c:59
eval at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/interpreter.c:207
jl_toplevel_eval_flex at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/toplevel.c:494
jl_f_top_eval at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/builtins.c:396
eval_user_input at REPL.jl:54
jlcall_eval_user_input;19884 at  (unknown line)
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/./julia.h:980
anonymous at task.jl:96
jl_apply at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/task.c:427
julia_trampoline at /Users/vagrant/tmp/julia-packaging/osx10.7+/julia-release-0.3/src/init.c:1007
Segmentation fault: 11
```

The code I used was the following:

``` julia
using DataFrames
using RDatasets
using Convex
using SCS

# we'll use iris data
# predict whether the iris species is versicolor using the sepal length and width and petal length and width
iris = dataset("datasets", "iris")
## outcome variable: +1 for versicolor, -1 otherwise
iris[:Y] = [species == "versicolor" ? 1.0 : -1.0 for species in iris[:Species]]
Y = array(iris[:Y])
## create data matrix with one column for each feature (first column corresponds to offset)
X = [ones(size(iris, 1)) iris[:SepalLength] iris[:SepalWidth] iris[:PetalLength] iris[:PetalWidth]];


function solve_convex(X, Y; paramGamma = 0)
    # # Solve the NLP using Convex.jl and SCS packages
    n, p = size(X)
        beta = Variable(p)
        mu = Variable()
        nu = Variable(n)
        problem = maximize(-logistic_loss(-Y.*(X*beta)) + paramGamma*mu + sum(nu))
        for (i = 1:n)
            problem.constraints += mu + nu[i] <= -2
            problem.constraints += nu[i] <= 0
        end
        problem.constraints += mu <= 0

    scs = SCSSolver((verbose=0))
    solve!(problem, scs)
    return(beta.value)

end

solve_convex(X, Y; paramGamma = 3)
```

Have you encountered such crashing out of Julia before?

**Comment by karanveerm** [comment]
I have only had one segfault before with 0.3.3. This is strange. I can't reproduce this consistently and sometimes it happens after I run the function 3-4 times. I commented out everything else in `solve!`, so we're probably doing something wrong with `conic_problem`. 

I did manage to get a "real error" message once:
```
ERROR: access to undefined reference
 in ht_keyindex2 at dict.jl:497
 in broadcast! at broadcast.jl:602
 in broadcast at broadcast.jl:234
 in + at /Users/karanveer/.julia/v0.3/Convex/src/conic_form.jl:34
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:110
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/constraints/constraints.jl:80
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/atoms/exp_cone/logsumexp.jl:52
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:46
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/constraints/constraints.jl:37
 in conic_form! at /Users/karanveer/.julia/v0.3/Convex/src/problems.jl:80
 in conic_problem at /Users/karanveer/.julia/v0.3/Convex/src/problems.jl:95
 in solve! at /Users/karanveer/.julia/v0.3/Convex/src/solution.jl:30
 in solve_convex at /Users/karanveer/.julia/v0.3/Convex/fail.jl:30
```

**Comment by daisy12321** [comment]
My experience is very similar to yours - the seg fault is not always consistent, and a few times I got the same "real error" message as well.

**Comment by joehuchette** [comment]
This may be off-base, but this may be because of a key mismatch between ``new_obj`` and ``d`` here: https://github.com/JuliaOpt/Convex.jl/blob/master/src/conic_form.jl#L26. This shouldn't be segfaulting in pure Julia code, though, so there's possibly a bug to be reported upstream.

**Comment by karanveerm** [comment]
I added `@show` statements before that line and got:
```julia
new_obj[var] => [1]
d[var] => [-0.0]
typeof(d[var]) => Array{Float64,2}
typeof(new_obj[var]) => Array{Int64,1}

signal (11): Segmentation fault: 11
...
```
so it doesn't seem like a key mismatch. broadcast seems to be doing some sort of caching https://github.com/JuliaLang/julia/blob/v0.3.3/base/broadcast.jl#L217
I can't tell since the file is completely uncommented.

**Comment by davidlizeng** [comment]
I've tried clearing out all global state maintained by Convex.jl in between runs and the segfault still happens on the second run, so I don't this this is an issue at the Convex.jl level. Something is probably happening in `broadcast`.

**Comment by joehuchette** [comment]
Whatever the cause, it would be good to try to get this down to a minimal working example, since this looks like it doesn't ever get to the point of touching the solver libraries, and pure julia code should never segfault. I'm not sure why caching the compiled methods would cause this, but I also can't make much of anything of the code.

**Comment by madeleineudell** [comment]
Is anyone still looking into this? If it's an issue in base julia (eg
broadcast) we should raise it there...

On Mon, Jan 19, 2015 at 6:32 PM, Joey Huchette <notifications@github.com>
wrote:

> Whatever the cause, it would be good to try to get this down to a minimal
> working example, since this looks like it doesn't ever get to the point of
> touching the solver libraries, and pure julia code should never segfault.
> I'm not sure why caching the compiled methods would cause this, but I also
> can't make much of anything of the code.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/51#issuecomment-70579675>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by daisy12321** [comment]
Running very similar code I've got some other "real error message" as below:

```
ERROR: cache not defined
 in broadcast! at broadcast.jl:600
 in broadcast at broadcast.jl:234
 in + at /Users/zhuo/.julia/v0.3/Convex/src/conic_form.jl:26
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:110
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:79
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/exp_cone/logsumexp.jl:52
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:46
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:79
 in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:62
 in conic_problem at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:72
 in solve! at /Users/zhuo/.julia/v0.3/Convex/src/solution.jl:13
 in solve_convex at /Users/zhuo/Documents/Github/robust_classification/logit/logit_func.jl:49
 in test_accu at /Users/zhuo/Documents/Github/robust_classification/logit/logit_func.jl:166
 in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
 in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
while loading /Users/zhuo/Documents/Github/robust_classification/logit/logit_3.jl, in expression starting on line 65
```

Hope this may help confirming whether it is an issue with base Julia.

**Comment by madeleineudell** [comment]
Which version of julia are you using? broadcast.jl doesn't seem to *have* a
line 600...

On Thu, Jan 22, 2015 at 1:55 PM, Daisy Zhuo <notifications@github.com>
wrote:

> Running very similar code I've got some other "real error message" as
> below:
>
> ERROR: cache not defined
>  in broadcast! at broadcast.jl:600
>  in broadcast at broadcast.jl:234
>  in + at /Users/zhuo/.julia/v0.3/Convex/src/conic_form.jl:26
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:110
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:79
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/exp_cone/logsumexp.jl:52
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:46
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/constraints/constraints.jl:79
>  in conic_form! at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:62
>  in conic_problem at /Users/zhuo/.julia/v0.3/Convex/src/problems.jl:72
>  in solve! at /Users/zhuo/.julia/v0.3/Convex/src/solution.jl:13
>  in solve_convex at /Users/zhuo/Documents/Github/robust_classification/logit/logit_func.jl:49
>  in test_accu at /Users/zhuo/Documents/Github/robust_classification/logit/logit_func.jl:166
>  in include at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
>  in include_from_node1 at /Applications/Julia-0.3.0.app/Contents/Resources/julia/lib/julia/sys.dylib
> while loading /Users/zhuo/Documents/Github/robust_classification/logit/logit_3.jl, in expression starting on line 65
>
> Hope this may help confirming whether it is an issue with base Julia.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/51#issuecomment-71106936>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by daisy12321** [comment]
Oh that's a good observation. I am running Version 0.3.0 (2014-08-20 20:43 UTC)

**Comment by madeleineudell** [comment]
well, that version also doesn't have a line 600. the error is coming from
some unfolded macro (which generates code, which creates new lines in the
``file'' on the fly). i'd raise this issue with base. my guess would be the
problem comes around line 217, with the line

@eval let cache = Dict{Function,Dict{Int,Dict{Int,Function}}}()

this function needs to be visible to whichever instance of broadcast! is
calling it, but for some reason is not visible.


On Thu, Jan 22, 2015 at 3:19 PM, Daisy Zhuo <notifications@github.com>
wrote:

> Oh that's a good observation. I am running Version 0.3.0 (2014-08-20 20:43
> UTC)
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/51#issuecomment-71119708>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by madeleineudell** [comment]
(actually, before raising on base, you should try out v0.3.5 and see if you
still experience the problem.)

On Thu, Jan 22, 2015 at 3:34 PM, Madeleine Udell <madeleine.udell@gmail.com>
wrote:

> well, that version also doesn't have a line 600. the error is coming from
> some unfolded macro (which generates code, which creates new lines in the
> ``file'' on the fly). i'd raise this issue with base. my guess would be the
> problem comes around line 217, with the line
>
> @eval let cache = Dict{Function,Dict{Int,Dict{Int,Function}}}()
>
> this function needs to be visible to whichever instance of broadcast! is
> calling it, but for some reason is not visible.
>
>
> On Thu, Jan 22, 2015 at 3:19 PM, Daisy Zhuo <notifications@github.com>
> wrote:
>
>> Oh that's a good observation. I am running Version 0.3.0 (2014-08-20
>> 20:43 UTC)
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/JuliaOpt/Convex.jl/issues/51#issuecomment-71119708>.
>>
>
>
>
> --
> Madeleine Udell
> PhD Candidate in Computational and Mathematical Engineering
> Stanford University
> www.stanford.edu/~udell
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by mlubin** [comment]
I can't seem to reproduce the issue on Linux using julia 0.3.6-pre or 0.4.0-dev. Is this specific to OS X?

**Comment by daisy12321** [comment]
I ran the code with Julia 0.3.3, on one MIT ORC Linux machine and got similar error message, 

```
signal (11): Segmentation fault
ht_keyindex2 at dict.jl:505
broadcast! at broadcast.jl:602
broadcast at broadcast.jl:234
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
+ at /usr3/zhuo/.julia/v0.3/Convex/src/conic_form.jl:27
jl_apply_generic at /usr/bin/../lib/x86_64-linux-gnu/julia/libjulia.so (unknown line)
```

**Comment by ajaykumar0712** [comment]
Hi I am Ajay.
I am facing a similar issue. I am attempting to solve a Geometric Programming problem.
I am aware that Julia does not have a GP mode unlike CVX 
I know how to reparameterize my objective function and I know that my objective function is concave.
So it can be maximized. 

I tried solving the problem but my terminal closes. I get the same Segmentation 11 Fault.
Could anyone suggest what should I do to fix this issue.

**Comment by joehuchette** [comment]
Could you provide a minimal, self-contained script that reproduces the segfault, as well as the output of ``versioninfo()``?

**Comment by ajaykumar0712** [comment]
Hi I will try and give a minimal script in a bit. Actually I am also going through the issue
[Github](sparse matrix \ causes gc segfault #10342)

**Comment by ajaykumar0712** [comment]
Sorry I meant the issue about sparse matrices [https://github.com/JuliaLang/julia/issues/10342]

**Comment by ajaykumar0712** [comment]
This is the Julia version I am using 
 `versioninfo()`

The output is

`Julia Version 0.3.6
 Commit a05f87b* (2015-01-08 22:33 UTC)
 Platform Info:
  System: Linux (i686-linux-gnu)
  CPU: Intel(R) Core(TM) i5-3230M CPU @ 2.60GHz
  BLAS: libopenblas (DYNAMIC_ARCH NO_AFFINITY Nehalem)
  LAPACK: libopenblas
  LIBM: libopenlibm
  LLVM: libLLVM-3.3`

**Comment by ajaykumar0712** [comment]
I am using the Convex package to perform a convex optimisation problem. 
I am sharing a sample of the code. This part attempts to find 

`p = 51 ## number of players
 lambda = Variable(p)  ## strength of player. This is what I am evaluating.

 obj = 0 ## The log likelihood
 ## Writing a loop to create the total log likelihood
 for i = 1:p
    for j = 1:p
        # Onjective function for simple Bradley Terry Model
        obj += wins[i, j]*(lambda[i] - Convex.logsumexp([lambda[i], lambda[j]]))
  end
end

## Solving the problem
problem = maximize(obj)
solve!(problem)`

But the output is as shown. I am not sure about what to do next.

signal (11): Segmentation fault
broadcast! at broadcast.jl:602
broadcast at broadcast.jl:234

jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
+ at /home/ajaykumar0712/.julia/v0.3/Convex/src/conic_form.jl:27
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:110
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/constraints/constraints.jl:86
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/exp_cone/logsumexp.jl:52
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:46
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/affine/multiply_divide.jl:70
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/constraints/constraints.jl:40
conic_form! at /home/ajaykumar0712/.julia/v0.3/Convex/src/problems.jl:80
conic_problem at /home/ajaykumar0712/.julia/v0.3/Convex/src/problems.jl:95
solve! at /home/ajaykumar0712/.julia/v0.3/Convex/src/solution.jl:29
julia_solve!_22378 at  (unknown line)
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
solve! at /home/ajaykumar0712/.julia/v0.3/Convex/src/solution.jl:10
julia_solve!_22373 at  (unknown line)
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: -1230549126)
unknown function (ip: -1230552888)
unknown function (ip: -1230485548)
unknown function (ip: -1230483017)
jl_load_file_string at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
include_string at /home/ajaykumar0712/.julia/v0.3/Jewel/src/eval.jl:32
jlcall_include_string_20316 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: -1230549126)
unknown function (ip: -1230552888)
unknown function (ip: -1230485548)
jl_f_top_eval at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
include_string at /home/ajaykumar0712/.julia/v0.3/Jewel/src/eval.jl:36
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
eval at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/eval.jl:11
evaldisplay at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/eval.jl:22
jlcall___evaldisplay#29___22089 at  (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
julia_evaldisplay_22088 at  (unknown line)
jlcall_evaldisplay_22088 at  (unknown line)
jl_f_kwcall at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
anonymous at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/eval.jl:53
handlecmd at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/LightTable.jl:65
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
handlenext at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/LightTable.jl:81
server at /home/ajaykumar0712/.julia/v0.3/Jewel/src/LightTable/LightTable.jl:22
jlcall_server_20078 at  (unknown line)
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
server at /home/ajaykumar0712/.julia/v0.3/Jewel/src/Jewel.jl:15
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_f_apply at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: -1230549126)
unknown function (ip: -1230552888)
unknown function (ip: -1230485548)
unknown function (ip: -1230483017)
jl_load at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_load_ at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
include at ./boot.jl:245
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
include_from_node1 at loading.jl:128
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
process_options at ./client.jl:285
_start at ./client.jl:354
jlcall__start_16871 at /usr/bin/../lib/i386-linux-gnu/julia/sys.so (unknown line)
jl_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
jl_apply_generic at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 134517404)
julia_trampoline at /usr/bin/../lib/i386-linux-gnu/julia/libjulia.so (unknown line)
unknown function (ip: 134516370)
__libc_start_main at /lib/i386-linux-gnu/libc.so.6 (unknown line)
unknown function (ip: 134516419)

**Comment by ajaykumar0712** [comment]
Hi I just forgot to mention that my W is a matrix of wins that player i has over player j. 
W is sparse. because most players have not played against each other

**Comment by ararslan** [comment]
I can't reproduce this following the example in the OP with Convex v0.7.0 and SCS v0.3.3 on Julia 0.6, so it seems it's since been fixed. Let me know if you come across it again.
