### ISSUE TITLE
diagm(Variable(n)) feature request

### ISSUE THREAD

**Issue by esproff** [JuliaOpt/Convex.jl#61]
Trying to put a variable vector into a diagonal matrix returns ERROR: `diagm` has no method matching diagm(::Variable).  I can certainly write my own routine for it, but if you all think it's a useful feature to have built in, then I would like to submit it as a feature request.  Thanks.

**Comment by karanveerm** [comment]
`diagm(x)` exists now for vector variables!

**Comment by Nate711** [comment]
diagm(::Variable) appears not to work any more.
`MethodError: no method matching diagm(::Variable)`

**Comment by blegat** [comment]
The method that works is `diagm(::Vector{Variable})`
