### ISSUE TITLE
operator_norm vs norm

### ISSUE THREAD

**Issue by rakeshvar** [JuliaOpt/Convex.jl#73]
Hi 

I am doing a problem (2.3 from [EE364B exercises](http://stanford.edu/class/ee364b/364b_exercises.pdf)) where I am trying to approximate B as a combination of A_i's. The approximation is in the operator norm. i.e. max singular value. 

Here is the code.

```julia
using Convex

srand(0)
n, p, q = 5, 3, 6
A = {randn(p, q) for _ in 1:n}
B = randn(p, q)

function diff(x)
	d = B
	for i in 1:n
		d -= x[i] * A[i]
	end
	return d
end

################### CVX 
xcvx = Variable(n)
problem = minimize(operator_norm(diff(xcvx)))
solve!(problem)

println("Status : ", problem.status)
println("Value : ", problem.optval)
u, d, v = svd(diff(xcvx.value))
println("X: ", xcvx.value, norm(diff(xcvx.value)), d[1])
fst = problem.optval
```

I am having to say operator_norm in stead of norm. If I say norm, cvx is minimizing something else. I think it should be consistent with underlying Julia where norm of a matrix is the operator norm by default.

**Comment by madeleineudell** [comment]
That's an excellent point. We will update `norm` in Convex.jl to be
consistent with the behavior in Base.

On Wed, Apr 8, 2015 at 1:02 AM, rakeshvar <notifications@github.com> wrote:

> Hi
>
> I am doing a problem (2.3 from EE364B exercises
> <http://stanford.edu/class/ee364b/364b_exercises.pdf>) where I am trying
> to approximate B as a combination of A_i's. The approximation is in the
> operator norm. i.e. max singular value.
>
> Here is the code.
>
> using Convex
> srand(0)
> n, p, q = 5, 3, 6
> A = {randn(p, q) for _ in 1:n}
> B = randn(p, q)
> function diff(x)
>     d = B
>     for i in 1:n
>         d -= x[i] * A[i]
>     end
>     return dend
> ################### CVX
> xcvx = Variable(n)
> problem = minimize(operator_norm(diff(xcvx)))solve!(problem)
> println("Status : ", problem.status)println("Value : ", problem.optval)
> u, d, v = svd(diff(xcvx.value))println("X: ", xcvx.value, norm(diff(xcvx.value)), d[1])
> fst = problem.optval
>
> I am having to say operator_norm in stead of norm. If I say norm, cvx is
> minimizing something else. I think it should be consistent with underlying
> Julia where norm of a matrix is the operator norm by default.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/73>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell
