### ISSUE TITLE
type MultiplyAtom has no field value: Simple Quadratic Program

### ISSUE THREAD

**Issue by ahwillia** [JuliaOpt/Convex.jl#79]
Not sure if this is the appropriate venue for this (do you check stackoverflow?) or if I'm making a basic mistake, but the simple problem:

<pre><code>using Convex
using SCS

P = [13 12 -2;
     12 17 6.;
     -2 6. 12]
q = [-22;-14.5;-13]
x = Variable(3)
p = minimize(0.5*dot(x,P*x) + q'*x + 1.0)
# This problem works: p = minimize(q'*x + 1.0)
p.constraints += [x <= 1; -x <= 1]
solve!(p)
</code></pre>

Generates the following error for me:

<pre>type MultiplyAtom has no field value
while loading In[1], in expression starting on line 16

 in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/multiply_divide.jl:89
 in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/multiply_divide.jl:70
 in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
 in conic_form! at /home/alex/.julia/v0.3/Convex/src/constraints/constraints.jl:40
 in conic_form! at /home/alex/.julia/v0.3/Convex/src/problems.jl:80
 in conic_problem at /home/alex/.julia/v0.3/Convex/src/problems.jl:95
 in solve! at /home/alex/.julia/v0.3/Convex/src/solution.jl:29
 in solve! at /home/alex/.julia/v0.3/Convex/src/solution.jl:10</pre>

Even though the objective function works:

    y = [1,2,3]
    0.5*dot(y,P*y) + q'*y + 1.0

(returns 59.5). I've tracked the issue down to the quadratic term... Again not sure if this is something wrong on my end, but any help appreciated.

**Comment by madeleineudell** [comment]
Convex is not able to infer that `dot(x,P*x)` is convex; but it should be
returning a better error message (that's a bug which we'll fix).

For you, the right fix is to use the `quad_form` function instead:
`quad_form(x,P)`.

On Thu, May 14, 2015 at 5:15 PM, Alex Williams <notifications@github.com>
wrote:

> Not sure if this is the appropriate venue for this (do you check
> stackoverflow?) or if I'm making a basic mistake, but the simple problem:
>
> using Convex
> using SCS
>
> P = [13 12 -2;
>      12 17 6.;
>      -2 6. 12]
> q = [-22;-14.5;-13]
> x = Variable(3)
> p = minimize(0.5*dot(x,P*x) + q'*x + 1.0)
> # This problem works: p = minimize(q'*x + 1.0)
> p.constraints += [x <= 1; -x <= 1]
> solve!(p)
>
> Generates the following error for me:
>
> type MultiplyAtom has no field value
> while loading In[1], in expression starting on line 16
>
>  in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/multiply_divide.jl:89
>  in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/multiply_divide.jl:70
>  in conic_form! at /home/alex/.julia/v0.3/Convex/src/atoms/affine/add_subtract.jl:106
>  in conic_form! at /home/alex/.julia/v0.3/Convex/src/constraints/constraints.jl:40
>  in conic_form! at /home/alex/.julia/v0.3/Convex/src/problems.jl:80
>  in conic_problem at /home/alex/.julia/v0.3/Convex/src/problems.jl:95
>  in solve! at /home/alex/.julia/v0.3/Convex/src/solution.jl:29
>  in solve! at /home/alex/.julia/v0.3/Convex/src/solution.jl:10
>
> Even though the objective function works reasonably:
>
> y = [1,2,3]
> 0.5*dot(y,P*y) + q'*y + 1.0
>
> (returns 59.5). I've tracked the issue down to the quadratic term... Again
> not sure if this is something wrong on my end, but any help appreciated.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/79>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by ahwillia** [comment]
Great! I knew it was something simple. Should I close this, or keep it open until the error message is improved?

**Comment by madeleineudell** [comment]
What version are you running? I believe Pkg.update() should fix the warning
message...

On Thu, May 14, 2015 at 8:58 PM, Alex Williams <notifications@github.com>
wrote:

> Great! I knew it was something simple. Should I close this, or keep it
> open until the error message is improved?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/79#issuecomment-102246921>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by jennyhong** [comment]
When you type `p = minimize(0.5*dot(x,P*x) + q'*x + 1.0)`, it already gives a warning saying:

`WARNING: Expression not DCP compliant`

because, as Madeleine said, we can't infer that `dot(x,P*x)` is convex. 

Convex.jl makes no guarantees for expressions that are not DCP compliant. We only throw warnings instead of erroring out, because I believe it is possible to write problems that are not DCP-compliant but can still be solved. 

That said, the warning should be more explicit. I have changed the error message to
`WARNING: Expression not DCP compliant. Trying to solve non-DCP compliant problems can lead to unexpected behavior.` (https://github.com/JuliaOpt/Convex.jl/commit/a702582881b70562574b8a9f5039daaa89a17db1) Also, this warning message will also show up when `solve!` is called, so it isn't lost among the warnings printed leading up to the final `solve!` call.
