### ISSUE TITLE
Missing partial trace

### ISSUE THREAD

**Issue by marcusps** [JuliaOpt/Convex.jl#80]
`Convex.jl` does not offer  a partial trace atom. [Partial traces](http://en.wikipedia.org/wiki/Partial_trace) are very common in physics applications (statistical mechanics, quantum information, condensed matter, etc), so it would be very helpful to have such a functionality in the library.

Although they are linear maps, they are _completely positive_ linear maps, meaning that they take a positive-semidefinite operator to another positive semi-definite operator even when acting on only part of an operator (i.e., a tensor product factor). As suggested in [this mailing list thread](https://groups.google.com/forum/#!topic/julia-opt/tgFfP1gb800), it seems like in order to take advantage of this property the partial trace would have to be implemented as an atom.

**Comment by marcusps** [comment]
I should add that most aspects of the atom appear straightforward to implement, it is just not entirely clear to me how to generate the appropriate conical forms, as the docs are somewhat light on how to add features to `Convex.jl`.

**Comment by madeleineudell** [comment]
yes, we need to add more info to the docs on how to add atoms. for now,
consider this recipe to make an atom implementing the function f(x):

* take a look at the nuclear norm atom
<https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/sdp_cone/nuclear_norm.jl>
for
an example of how to construct atoms, and see the norm atom
<https://github.com/JuliaOpt/Convex.jl/blob/master/src/atoms/norm.jl> for
an example of an atom that depends on a parameter.
* copy paste (eg) the nuclear norm file, replace anything saying nuclear
norm with the name of the atom f, fill in monotonicity, curvature, etc.
* the only mathematically interesting part is the conic_form! function.
following the example in the nuclear norm atom, you'll see that you can
just construct the problem whose optimal value is f(x), introducing any
auxiliary variables you need, exactly as you would normally in Convex.jl,
and then call cache_conic_form! on that problem.
* submit a PR, and we'll look it over, fix up anything that doesn't work,
and update these instructions to provide more clarity for future
contributors.

On Fri, May 22, 2015 at 6:16 AM, Marcus P S <notifications@github.com>
wrote:

> I should add that most aspects of the atom appear straightforward to
> implement, it is just not entirely clear to me how to generate the
> appropriate conical forms, as the docs are somewhat light on how to add
> features to Convex.jl.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/80#issuecomment-104657445>.
>



-- 
Madeleine Udell
PhD Candidate in Computational and Mathematical Engineering
Stanford University
www.stanford.edu/~udell

**Comment by thomasschiet** [comment]
I have implemented the partial trace and submitted a PR (#147).

**Comment by Ayush-iitkgp** [comment]
Shall we close this issue @madeleineudell ?
