### ISSUE TITLE
An example of model generation which is extremely slow in Convex.jl compared with cvxpy

### ISSUE THREAD

**Issue by boathit** [JuliaOpt/Convex.jl#82]
I tried to approximate a matrix A with a low rank matrix R through solving an convex optimization problem as follow, the `SCS` solver costs only 11.6s, however the model generation takes about 1218.2s

```julia
using Convex
using SCS

#A = readdlm("M.txt")
A = reshape(1:40000, 200, 200)
A[:,1] = 0
I = ifelse(A .== -1.0, 0.0, 1.0);
R = Variable(size(A))
problem = minimize( nuclear_norm(R), [vecnorm((R-A).*I) <= 2000] )

tic()
solve!(problem, SCSSolver(eps=1e-3, alpha=1.5))
toc()
```

In contrast with `Convex.jl`, the `cvxpy` does not suffer the same problem and is extremely fast, takes less 1s in model generation step

```python
import numpy as np
import pandas as pd
from cvxpy import *

#A = pd.read_csv("M.txt", delimiter="\t", header=None)
#A = A.values * 1.0
A = np.r_[1:40000+1:1].reshape(200,200).T
A[:,0] = 0
R = Variable(A.shape[0], A.shape[1])
I = np.where(A == -1.0, 0, 1.0)
problem = Problem(Minimize(norm(R,"nuc")), [norm(mul_elemwise(I,R-A), "fro") <= 2000])
problem.solve(solver=SCS, eps=1e-3, alpha=1.5, verbose=True)
 ```

The `Convex.jl` (version 0.0.5+) and `cvxpy` (version 0.2.19) share the same formulation of the optimization problem, why the performance of  `cvxpy` outperforms `Convex.jl` so much?

**Comment by madeleineudell** [comment]
The problem seems to be in the SCS interface. Replacing the `solve!` above with `conic_problem`, the code takes almost no time. The problem is that the SCS.jl interface doesn't yet use the new standard form for SDPs in the latest release,  and instead adds many unnecessary constraints to make the forms match. See [issue #14](https://github.com/JuliaOpt/SCS.jl/issues/14) on SCS.

**Comment by boathit** [comment]
@madeleineudell That's true, `conic_problem` is indeed very fast. And it seems not only `SCS.jl` cannot currently deal with SDP well, because when I switch the solver to `Mosek` like this `solve!(problem, MosekSolver())` the `MosekConicInterface.jl` throws an error "Invalid SDP cone definition". 

I check the source code in `MosekConicInterface.jl` and it seems that the issue has been reported here [issue #29](https://github.com/JuliaOpt/Mosek.jl/issues/29), "The issue seems to be that MOSEK expects a n(n+1)/2 indexes for an nn semidefinite variable (or constraint), and Convex.jl gives it n*n indexes."

**Comment by mlubin** [comment]
@boathit, that's correct, Mosek doesn't currently work for SDPs with Convex.jl

**Comment by madeleineudell** [comment]
Mosek now works for SDPs with Convex.jl. Give it a try and see if it's still slow. (I expect it should be *much* faster than before.)

**Comment by boathit** [comment]
Yeah, it's true now Mosek works well with Convex.jl. But with the same test case above, the bottleneck now seems to be Mosek,  it requires as large as 32GB memory and is slow. By contrast, SCS Solver only needs 100MB memory and is dramatically fast. I guess perhaps the significant difference comes from the implementation behind the solvers, Mosek trys to use interior point method to solve the SDPs while SCS adopts Alternating Direction Method of  Multipliers which could handle the problem easily, so I really miss SCS.jl which currently fails to work

```julia
using Convex
#using SCS
using Mosek

#A = readdlm("M.txt")
A = reshape(1:40000, 200, 200)
A[:,1] = 0
I = ifelse(A .== -1.0, 0.0, 1.0);
R = Variable(size(A))
problem = minimize( nuclear_norm(R), [vecnorm((R-A).*I) <= 2000] )

tic()
solve!(problem, MosekSolver())
toc()
```

**Comment by madeleineudell** [comment]
We're working on getting SCS up and running with Convex.jl again; it should be up within a week. See JuliaOpt/SCS.jl#14.

If you need it in the meantime I can send installation instructions, but no guarantees that the solver will produce the right answer. (It fails for a few of our test cases.)

**Comment by boathit** [comment]
Great, that would be nice.

2015-06-15 11:57 GMT+08:00 Madeleine Udell <notifications@github.com>:

**Comment by madeleineudell** [comment]
Ok! In that case:

* clone [scs](https://github.com/cvxgrp/scs)
* in the scs directory,
    * edit `scs.mk` to set the `use_lapack` and `dlong` flags to `1`.
    * `make` scs
* in the `SCS.jl` directory (probably `~/.julia/v0.3/SCS`), edit `deps/deps.jl` to point to the version of SCS you compiled, ie, the last line of the file should read something like 
```
@checked_lib scs "<scsdir>/out/libscsdir.dylib"
```

Now everything should work. (Modulo occasional numerical errors, as I mentioned above.)

**Comment by boathit** [comment]
Madeleine, thank you so much!

2015-06-15 13:01 GMT+08:00 Madeleine Udell <notifications@github.com>:
