### ISSUE TITLE
simplify atom names

### ISSUE THREAD

**Issue by madeleineudell** [JuliaOpt/Convex.jl#87]
I don't like typing underscores. Furthermore, Julia's convention is not to use them except when they are necessary for names to be comprehended. It would also be easier to remember atom names if they all adhere to the same (no underscore) convention. Hence, I suggest the following changes:
- `lambda_max` -> `lambdamax`
- `lambda_min` -> `lambdamin`
- `sum_largest` -> `sumlargest`
- `geo_mean` -> `geomean`

etc. In fact, I don't see a single atom that truly _needs_ its underscore. Any objections?

**Comment by IainNZ** [comment]
:+1:

**Comment by tkelman** [comment]
+1, though a mass-renaming would call for at least bumping the minor version number

**Comment by madeleineudell** [comment]
Yes, but we're due for that anyway after this SDP convention change works
consistently with both SCS and Mosek. In fact, at that point I think it
could be argued that we're ready for v0.1.0.

On Sun, Jun 14, 2015 at 8:02 PM, Tony Kelman <notifications@github.com>
wrote:

> +1, though a mass-renaming would call for at least bumping the minor
> version number
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/87#issuecomment-111908097>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell
