### ISSUE TITLE
Problems with l1 trend filtering using Convex.jl

### ISSUE THREAD

**Issue by thanos-mad-titan** [JuliaOpt/Convex.jl#91]
I am trying to work on building the wonderful [l1 trend filtering](https://web.stanford.edu/~boyd/l1_tf/) algorithm by Stephen Boyed et.al.  in Julia. I am using Convex.jl backed by ECOS solver for this. The algorithm has problems when I use Convex.jl. ECOS which uses the same interior point method as the one used in original l1_tf in matlab, fails to reach convergence and stops without a solution. I am not sure if I am using the convex solvers wrong or is the solvers themselves creating this incorrectness?

 Attached is the code using the snp500 which is used in the example in the original C code in [snp500.txt](https://web.stanford.edu/~boyd/l1_tf/C/snp500.txt)

``` julia
using Convex
using Gadfly
using ECOS


function l1_tf(y, lambda)
  n = length(yin);
  I = eye(n -2, n - 2);
  O = zeros(n - 2, 1);
  D = [I O O] + [O -2 * I O] + [O O I];
  yvec = yin[:, 1];

  lambdamax = norm((D * D')\(D * yvec), Inf);
  x = Variable(n);
  problem = minimize(0.5 * (norm(yvec - x, 2) ^ 2) + lambda * norm(D * x, 1));

  solve!(problem, ECOSSolver())

  xopt = evaluate(x)
  return xopt
end

yin = readcsv("snp500.txt");
yvec = yin[:, 1];
lambda = 50;

xopt = l1_tf(yvec, lambda);

plot(layer(x = collect(1:n), y = yvec, Geom.point),
      layer(x = collect(1:n), y = xopt, Geom.line))
```

**Comment by mlubin** [comment]
Could you include the iteration log from ECOS? Use ``ECOSSolver(verbose=1)``.

**Comment by thanos-mad-titan** [comment]
Here is the verbose log for ECOS. Appreciate your help. Do let me know if you need more info.

```
ECOS 1.0.5 - (c) A. Domahidi, ETH Zurich & embotech 2012-14. Support: ecos@embot
ech.com

It     pcost       dcost      gap   pres   dres    k/t    mu     step    IR
 0  +1.274e-12  -1.291e+00  +1e+05  7e+01  2e+00  1e+00  2e+01   N/A    1 1 -
 1  -1.915e+00  -1.561e+00  +5e+03  7e+00  2e-01  6e-01  1e+00  0.9533  5 5 5
 2  -1.153e-01  -1.017e-01  +2e+02  2e-01  7e-03  2e-02  4e-02  0.9674  5 5 5
 3  -1.028e-01  -8.202e-02  +1e+02  2e-01  6e-03  3e-02  3e-02  0.2238  5 5 5
 4  -8.324e-02  -5.345e-02  +1e+02  2e-01  5e-03  3e-02  3e-02  0.2520  5 5 5
 5  -1.033e-02  +2.606e-02  +9e+01  1e-01  4e-03  4e-02  2e-02  0.3566  5 5 5
 6  +2.160e-01  +2.437e-01  +5e+01  7e-02  2e-03  3e-02  1e-02  0.6591  2 1 2
 7  +2.722e-01  +2.951e-01  +3e+01  5e-02  1e-03  2e-02  8e-03  0.5096  1 1 1
 8  +2.285e-01  +2.512e-01  +3e+01  5e-02  1e-03  2e-02  8e-03  0.0379  0 1 1
 9  +3.324e-01  +3.519e-01  +2e+01  3e-02  9e-04  2e-02  5e-03  0.9899  1 1 1
10  +2.283e-01  +2.426e-01  +1e+01  2e-02  6e-04  1e-02  4e-03  0.3555  0 0 1
11  -4.213e-02  -3.200e-02  +1e+01  2e-02  5e-04  1e-02  3e-03  0.9899  1 1 1
12  +6.338e-01  +6.388e-01  +5e+00  8e-03  2e-04  5e-03  1e-03  0.9214  1 1 1
13  +6.953e-01  +6.982e-01  +3e+00  5e-03  1e-04  3e-03  7e-04  0.6988  1 0 2
14  +6.377e-01  +6.406e-01  +3e+00  5e-03  1e-04  3e-03  7e-04  0.0147  1 1 1
15  +3.359e-01  +3.386e-01  +3e+00  4e-03  1e-04  3e-03  6e-04  0.2322  1 1 1
16  +5.058e-01  +5.084e-01  +2e+00  4e-03  1e-04  3e-03  6e-04  0.2169  3 1 3
17  +6.714e-01  +6.729e-01  +1e+00  2e-03  7e-05  2e-03  3e-04  0.9899  2 0 1
18  +5.325e-01  +5.340e-01  +1e+00  3e-03  6e-05  2e-03  3e-04  0.0407  0 0 0
19  +8.836e-01  +8.848e-01  +6e-01  3e-03  5e-05  1e-03  2e-04  0.6303  1 1 1
20  +8.654e-01  +8.665e-01  +6e-01  3e-03  5e-05  1e-03  2e-04  0.0001  0 0 1
No further progress possible, recovering best iterate (17) and stopping.
NUMERICAL PROBLEMS (reached feastol=2.3e-03, reltol=1.7e+00, abstol=1.2e+00).
Runtime: 0.611462 seconds.

WARNING: Problem status Error; solution may be inaccurate.
```

**Comment by madeleineudell** [comment]
Thanos, I'm not sure why ECOS would be having trouble with this problem.
SCS solves the problem fine, so perhaps you should raise the issue on the
ECOS repository?

For completeness, here's a revision of the code snippet Thanos included
above to show how to solve the problem with SCS:
```
using Convex, SCS

lambda = 50
yin = readcsv("snp500.txt")

n = length(yin)
I = speye(n -2, n - 2);
O = spzeros(n - 2, 1);
D = [I O O] + [O -2 * I O] + [O O I];
yvec = yin[:, 1];

x = Variable(n);
problem = minimize(0.5 * (norm(yvec - x, 2) ^ 2) + lambda * norm(D * x, 1));

solve!(problem, SCSSolver())
```

On Thu, Jul 2, 2015 at 7:55 PM, Thanos <notifications@github.com> wrote:

> Here is the verbose log for ECOS. Appreciate your help. Do let me know if
> you need more info.
>
> ECOS 1.0.5 - (c) A. Domahidi, ETH Zurich & embotech 2012-14. Support: ecos@embotech.com
>
> It     pcost       dcost      gap   pres   dres    k/t    mu     step    IR
>  0  +1.274e-12  -1.291e+00  +1e+05  7e+01  2e+00  1e+00  2e+01   N/A    1 1 -
>  1  -1.915e+00  -1.561e+00  +5e+03  7e+00  2e-01  6e-01  1e+00  0.9533  5 5 5
>  2  -1.153e-01  -1.017e-01  +2e+02  2e-01  7e-03  2e-02  4e-02  0.9674  5 5 5
>  3  -1.028e-01  -8.202e-02  +1e+02  2e-01  6e-03  3e-02  3e-02  0.2238  5 5 5
>  4  -8.324e-02  -5.345e-02  +1e+02  2e-01  5e-03  3e-02  3e-02  0.2520  5 5 5
>  5  -1.033e-02  +2.606e-02  +9e+01  1e-01  4e-03  4e-02  2e-02  0.3566  5 5 5
>  6  +2.160e-01  +2.437e-01  +5e+01  7e-02  2e-03  3e-02  1e-02  0.6591  2 1 2
>  7  +2.722e-01  +2.951e-01  +3e+01  5e-02  1e-03  2e-02  8e-03  0.5096  1 1 1
>  8  +2.285e-01  +2.512e-01  +3e+01  5e-02  1e-03  2e-02  8e-03  0.0379  0 1 1
>  9  +3.324e-01  +3.519e-01  +2e+01  3e-02  9e-04  2e-02  5e-03  0.9899  1 1 1
> 10  +2.283e-01  +2.426e-01  +1e+01  2e-02  6e-04  1e-02  4e-03  0.3555  0 0 1
> 11  -4.213e-02  -3.200e-02  +1e+01  2e-02  5e-04  1e-02  3e-03  0.9899  1 1 1
> 12  +6.338e-01  +6.388e-01  +5e+00  8e-03  2e-04  5e-03  1e-03  0.9214  1 1 1
> 13  +6.953e-01  +6.982e-01  +3e+00  5e-03  1e-04  3e-03  7e-04  0.6988  1 0 2
> 14  +6.377e-01  +6.406e-01  +3e+00  5e-03  1e-04  3e-03  7e-04  0.0147  1 1 1
> 15  +3.359e-01  +3.386e-01  +3e+00  4e-03  1e-04  3e-03  6e-04  0.2322  1 1 1
> 16  +5.058e-01  +5.084e-01  +2e+00  4e-03  1e-04  3e-03  6e-04  0.2169  3 1 3
> 17  +6.714e-01  +6.729e-01  +1e+00  2e-03  7e-05  2e-03  3e-04  0.9899  2 0 1
> 18  +5.325e-01  +5.340e-01  +1e+00  3e-03  6e-05  2e-03  3e-04  0.0407  0 0 0
> 19  +8.836e-01  +8.848e-01  +6e-01  3e-03  5e-05  1e-03  2e-04  0.6303  1 1 1
> 20  +8.654e-01  +8.665e-01  +6e-01  3e-03  5e-05  1e-03  2e-04  0.0001  0 0 1
> No further progress possible, recovering best iterate (17) and stopping.
> NUMERICAL PROBLEMS (reached feastol=2.3e-03, reltol=1.7e+00, abstol=1.2e+00).
> Runtime: 0.611462 seconds.
>
> WARNING: Problem status Error; solution may be inaccurate.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/JuliaOpt/Convex.jl/issues/91#issuecomment-118215751>.
>



-- 
Madeleine Udell
www.stanford.edu/~udell
