### ISSUE TITLE
Multidimensional arrays feature request

### ISSUE THREAD

**Issue by jacobbien** [JuliaOpt/Convex.jl#93]
It would be convenient to have three-dimensional arrays as variables.  For example,

`x = Variable(n, p, m)`

would be great for problems in which you are optimizing over (say) `m` matrices that are each `n` by `p`.  Functions such as `sum(x, k)` would extend in the natural way.

**Comment by madeleineudell** [comment]
If the 3D construction is just being used to store data more conveniently, note that you can also put variables (of any size) into an array of variables:
```
julia> array_o_vars = Variable[Variable(3,4) for i=1:5]
5-element Array{Variable,1}:
 Variable of
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()
 Variable of
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()
 Variable of
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()
 Variable of
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()
 Variable of
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()

julia> sum(array_o_vars)
AbstractExpr with
head: +
size: (3, 4)
sign: NoSign()
vexity: AffineVexity()
```
We've been reluctant to add multidimensional arrays because our syntax focuses on linear algebraic operations, which extend only messily to higher dimensions.

**Comment by jacobbien** [comment]
Ah, that's perfect.  Never mind about my feature request.  Thanks!

**Comment by wangg12** [comment]
How can I get a variable with higher dimensions? For example, I want to get a variable with the size of (2,2,2,2,2).

**Comment by madeleineudell** [comment]
You can extend the idea above using any standard Julia syntax. For example, the following makes an array of variables of size (2,2,2,2,2)
```
reshape(Variable[Variable() for i=1:2^5], 2,2,2,2,2)
```
