### ISSUE TITLE
Solve Feasability Problems

### ISSUE THREAD

**Issue by ahwillia** [JuliaOpt/Convex.jl#94]
Is there a way to solve problems with a constant objective function (i.e. feasability problems)? Simple example:

```julia
x = Variable()
minimize(0.0, x>0)
```

**Error:** `minimize` has no method matching `minimize(::Constant, ::(GtConstraint,))`.

**Comment by madeleineudell** [comment]
Yes: [satisfy](http://convexjl.readthedocs.org/en/latest/types.html#problem)

But the problem above shouldn't result in an error; we'll fix that shortly.
